### ISSUE TITLE
Cannot read property 'log' of undefined

### ISSUE THREAD

**Issue by skitzow88** [grzegorz914/homebridge-xbox-tv#1]
(node:3867) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
0|homebridge -I  |     at /usr/lib/node_modules/homebridge-xbox-tv/index.js:101:9
0|homebridge -I  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|homebridge -I  | (node:3867) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
0|homebridge -I  | (node:3867) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by grzegorz914** [comment]
fixed
