### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by joffreyha** [grzegorz914/homebridge-xbox-tv#10]
Hi,

Since using v0.1.9 I see the following error occasional in the logs:
[4/8/2020, 12:38:23 PM] [XboxTv] Device: 192.x.x.x, name: Xbox-L, state: Offline
(node:447) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_discovery_response listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:447) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
[4/8/2020, 12:38:33 PM] [XboxTv] Device: 192.x.x.x, name: Xbox-L, state: Offline
(node:447) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_timeout listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit

Config as before:
 "devices": [
                {
                    "name": "Xbox-L",
                    "host": "192.x.x.x",
                    "xboxliveid": "FD0xxx",
                    "switchInfoMenu": false
                }
            ],
            "platform": "XboxTv"

**Comment by grzegorz914** [comment]
This is from 3rd SDK package (smartglass), I can not fix them in my plugin, we need to wait for fix from the SDK author. Right now can be ignored.

**Comment by MrRizzles** [comment]
Have been unable to get it setup due to this as well unfortunately.

ReferenceError: error is not defined
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:188:40)
    at EventEmitter.emit (events.js:323:22)
    at EventEmitter.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/events.js:116:27)
    at EventEmitter.emit (events.js:311:20)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-smartglass-core-node/src/smartglass.js:264:30)
    at Socket.emit (events.js:311:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)

**Comment by grzegorz914** [comment]
Fixed in 0.1.12

**Comment by joffreyha** [comment]
Hi @grzegorz914, i've just updated and again got an error, here a part of the log after the update:

[37m[4/13/2020, 4:43:28 PM][39m [36m[XboxTv][39m Device: 192.168.1.55, name: Xbox-L1, state: Offline
[0;37m[4/13/2020, 4:43:33 PM] [0m[0;36m[Config][0m Running Command: sudo -E -n npm install --save homebridge-xbox-tv@latest
[37m[4/13/2020, 4:43:38 PM][39m [36m[XboxTv][39m Device: 192.168.1.55, name: Xbox-L1, state: Offline
[0;37m[4/13/2020, 4:44:20 PM] [0m[0;36m[Config][0m Homebridge restart request received
[0;37m[4/13/2020, 4:44:20 PM] [0m[0;36m[Config][0m UI / Bridge settings have not changed; only restarting Homebridge process
[37m[4/13/2020, 4:44:20 PM][0m [36m[HB Supervisor][0m Sending SIGTERM to Homebridge
[37m[4/13/2020, 4:44:20 PM][39m Got SIGTERM, shutting down Homebridge...
[37m[4/13/2020, 4:44:20 PM][39m [36m[Sonos][39m closed http://192.168.1.11:44011/notify
[37m[4/13/2020, 4:44:25 PM][0m [36m[HB Supervisor][0m Homebridge Process Ended. Code: 143, Signal: null
[37m[4/13/2020, 4:44:30 PM][0m [36m[HB Supervisor][0m Restarting Homebridge...
[37m[4/13/2020, 4:44:30 PM][0m [36m[HB Supervisor][0m Starting Homebridge with extra flags: -P /homebridge/node_modules
[37m[4/13/2020, 4:44:30 PM][0m [36m[HB Supervisor][0m Started Homebridge with PID: 2122
[37m[4/13/2020, 4:44:31 PM][39m Loaded config.json with 0 accessories and 5 platforms.
[37m[4/13/2020, 4:44:31 PM][39m ---
[37m[4/13/2020, 4:44:32 PM][39m Loaded plugin: homebridge-camera-ffmpeg
[37m[4/13/2020, 4:44:32 PM][39m Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[37m[4/13/2020, 4:44:32 PM][39m ---
[37m[4/13/2020, 4:44:32 PM][39m Loaded plugin: homebridge-sss-platform
[37m[4/13/2020, 4:44:32 PM][39m Registering platform 'homebridge-sss-platform.sss-platform'
[37m[4/13/2020, 4:44:32 PM][39m ---
[37m[4/13/2020, 4:44:32 PM][39m Loaded plugin: homebridge-xbox-tv
[37m[4/13/2020, 4:44:32 PM][39m Registering platform 'homebridge-xbox-tv.XboxTv'
[37m[4/13/2020, 4:44:32 PM][39m ---
[37m[4/13/2020, 4:44:32 PM][39m Loaded plugin: homebridge-zp
[37m[4/13/2020, 4:44:32 PM][39m Registering platform 'homebridge-lib.Lib'
[37m[4/13/2020, 4:44:32 PM][39m Registering platform 'homebridge-zp.ZP'
[37m[4/13/2020, 4:44:32 PM][39m ---
[37m[4/13/2020, 4:44:32 PM][39m Loaded plugin: homebridge-config-ui-x
[37m[4/13/2020, 4:44:32 PM][39m Registering platform 'homebridge-config-ui-x.config'
[37m[4/13/2020, 4:44:32 PM][39m ---
[37m[4/13/2020, 4:44:32 PM][39m Loading 5 platforms...
[37m[4/13/2020, 4:46:04 PM][39m [36m[XboxTv][39m Device: 192.168.1.55, name: Xbox-L1, state: Offline
(node:2122) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_discovery_response listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
(node:2122) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
[37m[4/13/2020, 4:46:14 PM][39m [36m[XboxTv][39m Device: 192.168.1.55, name: Xbox-L1, state: Offline

This was an inline update via homebridge-config-ui-x to homebridge-xbox-tv v0.1.12, anything else I should do, can help with?

Thx

**Comment by joffreyha** [comment]
Ps. a Docker clear and reinstall also throws error:

[4/13/2020, 9:46:24 PM] [XboxTv] Device: 192.168.1.55, name: Xbox-L1, state: Offline                                                                
(node:495) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_discovery_response listeners added to [EventEmitter]. Use
 emitter.setMaxListeners() to increase limit                                                                                                        
(node:495) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emi
tter.setMaxListeners() to increase limit

**Comment by grzegorz914** [comment]
please check latest ver. 0.1.31

**Comment by joffreyha** [comment]
No errors since 12 hrs, docker clear also good, looks good!

**Comment by grzegorz914** [comment]
OK, i close this, if some happen feel free to open.
