### ISSUE TITLE
xbox never turns on

### ISSUE THREAD

**Issue by starkstrom-de** [grzegorz914/homebridge-xbox-tv#106]
Using latest version 1.8.7, with an xbox series x. 
logs show plug-in gives frequent feedback on power state:
[02/11/2021, 13:13:15] [XboxTv] Device: 192.168.1.124 Xbox Series X, get Power state successful: OFF
[02/11/2021, 13:13:16] [XboxTv] Device: 192.168.1.124 Xbox Series X, get Power state successful: OFF
[02/11/2021, 13:22:48] [XboxTv] Device: 192.168.1.124 Xbox Series X, get Power state successful: OFF

Tapping the xbox tile make it light up for a few seconds, but nothing happens. the log shows no entries to try to change power state, etc.. 

I have confirmed that access is allowed for all apps, and also confirmed the xbox is in instant-on power mode.

My config is shown below. When I turn on the xbox with the controller, then the HomeKit tile lights up, so it apparently knows of the "on" state. I can then also turn it off by tapping the tile, so that part works fine.
This is shown here: turned on with controller, then turned off with HomeKit tile:

[02/11/2021, 12:54:17] [XboxTv] Device: 192.168.1.124 Xbox Series X, get Input successful, input: Settings, reference: Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application, oneneStoreProductId: Settings
[02/11/2021, 12:54:17] [XboxTv] Device: 192.168.1.124 Xbox Series X, get Power state successful: ON
[02/11/2021, 12:54:23] [XboxTv] Device: 192.168.1.124 Xbox Series X, set Power successful, OFF

I just cannot ever turn it on via HomeKit.

                    "name": "Xbox Series X",
                    "host": "192.168.1.124",
                    "xboxliveid": "F***************",
                    "xboxWebApiToken": "M.R3_BL2.06be949a-01ab-35f3-ea3b-25cbc90202f4",
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "webApiControl": true,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "rebootControl": false,
                    "getInputsFromDevice": true,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": true,
                    "inputs": [
                        {
                            "name": "Apple TV",
                            "reference": "AppleInc.AppleTV_nzyj5cx40ttqa!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Dashboard",
                            "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                            "type": "HOME_SCREEN"
                        },
                        {
                            "name": "Amazon Music",
                            "reference": "AmazonMobileLLC.AmazonMusicXbox_kc6t79cpj4tp0!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Plex",
                            "reference": "CAF9E577.PlexforXbox_aam28m9va5cke!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Amazon Prime",
                            "reference": "AmazonVideo.AmazonVideo_pwbj9vvecjh7j!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Netflix",
                            "reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "YouTubeTV",
                            "reference": "GoogleInc.YouTubeTV_yfg5n0ztvskxp!App",
                            "type": "APPLICATION"
                        }
                    ],
                    "manufacturer": "Microsoft Corporation"
                }
            ],
            "platform": "XboxTv"

**Comment by grzegorz914** [comment]
Enable debug mode and try to power ON, then get the log.

**Comment by starkstrom-de** [comment]
Thank you, did that, output shows 'device_unavailable'.

Very weird. I have confirmed that the xbox indeed is on that IP address (wifi connection), so that's very strange:


[02/11/2021, 14:08:56] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug update device state.
[02/11/2021, 14:09:01] [XboxTv] Device: 192.168.1.124 Xbox Series X, connect error: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.1.124'
}
[02/11/2021, 14:09:01] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug update device state.
[02/11/2021, 14:09:05] [homebridge-xbox-tv] Error: 
    at Accessory.sendCharacteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1876:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1583:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[02/11/2021, 14:09:06] [XboxTv] Device: 192.168.1.124 Xbox Series X, connect error: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.1.124'
}
[02/11/2021, 14:09:06] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug update device state.
[02/11/2021, 14:09:08] [XboxTv] Device: 192.168.1.124 Xbox Series X, set Power, error: {
  status: 'error_discovery',
  error: 'Console was not found on network. Probably failed'
}
[02/11/2021, 14:09:11] [XboxTv] Device: 192.168.1.124 Xbox Series X, connect error: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.1.124'
}
[02/11/2021, 14:09:11] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug update device state.
[02/11/2021, 14:09:16] [XboxTv] Device: 192.168.1.124 Xbox Series X, connect error: {
  error: 'device_unavailable',
  message: 'Xbox is unavailable on 192.168.1.124'
}

**Comment by grzegorz914** [comment]
Looks like console in not on network, so cannot be power ON.

**Comment by starkstrom-de** [comment]
so when not in debug mode the messages show:
[02/11/2021, 12:54:23] [XboxTv] Device: 192.168.1.124 Xbox Series X, set Power successful, OFF

when debug mode is enabled, it shows:
[02/11/2021, 14:09:11] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug update device state.
[02/11/2021, 14:09:16] [XboxTv] Device: 192.168.1.124 Xbox Series X, connect error: {
error: 'device_unavailable',
message: 'Xbox is unavailable on 192.168.1.124'

Seems odd, no? I mean the xbox IS online, otherwise I would not be able to watch TV on it, or perform any other action on it. it's logged in and online. In addition, I can turn it "off" via HomeKit when it was turned on via the controller.

I use a mesh network, both 2.4 & 5 gig bands (Orbi devices), could that have anything to do with the discovery problem? Or could a NAT issue impede discovery?

**Comment by starkstrom-de** [comment]
Further, when I ran the debug log, the xbox was turned OFF, but in standby mode. I tried to ping the console, and could not ping it. So I just turned the console on and can now ping it, and the debug output shows as follows:

[02/11/2021, 15:01:27] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug mediaStateData: { title_id: 0 }
[02/11/2021, 15:01:27] [XboxTv] Device: 192.168.1.124 Xbox Series X, requesting device info.
[02/11/2021, 15:01:27] [XboxTv] Device: 192.168.1.124 Xbox Series X, Connected.
[02/11/2021, 15:01:27] [XboxTv] -------- Xbox Series X --------
[02/11/2021, 15:01:27] [XboxTv] Manufacturer: Microsoft Corporation
[02/11/2021, 15:01:27] [XboxTv] Model: Model Name
[02/11/2021, 15:01:27] [XboxTv] Serialnr: F4000DB6B85ACE04
[02/11/2021, 15:01:27] [XboxTv] Firmware: 10.0.22000
[02/11/2021, 15:01:27] [XboxTv] ----------------------------------
[02/11/2021, 15:01:27] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug writeDevInfo: {
  "manufacturer": "Microsoft Corporation",
  "modelName": "Model Name",
  "serialNumber": "F4000DB6B85ACE04",
  "firmwareRevision": "10.0.22000"
}
[02/11/2021, 15:01:27] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug update device state.
}, apps: {
  title_id: 750323071,
  flags: <Buffer 80 00>,
  product_id: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
  sandbox_id: <Buffer 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>,
  aum_id: 'Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application'
}, xbox: {
  _ip: '192.168.1.124',
  _certificate: <Buffer 30 82 02 47 30 82 01 2f a0 03 02 01 02 02 10 2f cf 13 56 ae 65 f8 47 a0 94 66 df 97 e2 b5 e0 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 25 31 23 ... 537 more bytes>,
  _iv: false,
  _liveid: 'F4000DB6B85ACE04',
  _is_authenticated: false,
  _participantid: 6,
  _connection_status: false,
  _request_num: 48,
  _target_participant_id: 0,
  _source_participant_id: 6,
  _fragments: {},
  _crypto: [Object],
  getIp: [Function: getIp],
  getCertificate: [Function: getCertificate],
  getLiveid: [Function: getLiveid],
  setLiveid: [Function: setLiveid],
  get_requestnum: [Function: get_requestnum],
  set_participantid: [Function: set_participantid],
  connect: [Function: connect],
  loadCrypto: [Function: loadCrypto]
}, remote: { address: '192.168.1.124', family: 'IPv4', port: 5050, size: 186 }, smartglass: {
  _client_id: 92,
  _console: [Object],
  _socket: [Socket],
  _events: [EventEmitter],
  _last_received_time: 1635890607,
  _is_broadcast: false,
  _ip: '192.168.1.124',
  _interval_timeout: Timeout {
    _idleTimeout: 1000,
    _idlePrev: [Timeout],
    _idleNext: [TimersList],
    _idleStart: 136076,
    _onTimeout: [Function: bound ],
    _timerArgs: undefined,
    _repeat: 1000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 1679,
    [Symbol(triggerId)]: 1674
  },
  _managers: [Object],
  _managers_num: 3,
  _connection_status: true,
  _current_app: 'Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application',
  discovery: [Function: discovery],
  getActiveApp: [Function: getActiveApp],
  isConnected: [Function: isConnected],
  powerOn: [Function: powerOn],
  powerOff: [Function: powerOff],
  connect: [Function: connect],
  on: [Function: on],
  disconnect: [Function: disconnect],
  recordGameDvr: [Function: recordGameDvr],
  addManager: [Function: addManager],
  getManager: [Function: getManager],
  _getSocket: [Function: _getSocket],
  _closeClient: [Function: _closeClient],
  _send: [Function: _send]
}
[02/11/2021, 15:03:27] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug mediaStateData: { title_id: 0 }
[02/11/2021, 15:03:27] [XboxTv] Device: 192.168.1.124 Xbox Series X, debug update device state.


What do you make of this info? Is there something preventing the xbox to be accessible when in standby mode?

**Comment by grzegorz914** [comment]
In your case the console is not available on network in standby mode, as long the console is not connected to the network cannot be powered ON.  Looks like the instant power on is not enabled or not working correct or the console lost connection to the network in standby.

**Comment by starkstrom-de** [comment]
Okay, I will keep messing around and see if I can figure out why this is happening.
thanks for your time!

**Comment by many7695** [comment]
> Okay, I will keep messing around and see if I can figure out why this is happening.
> thanks for your time!

Im having the same issue as u are if u figure it out please let me know

**Comment by starkstrom-de** [comment]
> > Okay, I will keep messing around and see if I can figure out why this is happening.
> > thanks for your time!
> 
> Im having the same issue as u are if u figure it out please let me know

I am curious...when your xbox is in stand-by mode, can you ping it with a response? Mine times out, which probably means that my home bridge cannot find/connect to it. Let me know pls.

**Comment by many7695** [comment]
> > > Okay, I will keep messing around and see if I can figure out why this is happening.
> > > thanks for your time!
> > 
> > 
> > Im having the same issue as u are if u figure it out please let me know
> 
> I am curious...when your xbox is in stand-by mode, can you ping it with a response? Mine times out, which probably means that my home bridge cannot find/connect to it. Let me know pls.

So far when my xbox is on I have no issues with it timing out it but once I turned it off that's when the issue start I'm new to homebridge maybe less the 4 days using it i was hoping I could get this  to work like I have the Google assistant working with the xbox

**Comment by grzegorz914** [comment]
try 1.8.8 please

**Comment by many7695** [comment]
> try 1.8.8 please

Thank u updating to 1.8.8 worked towards turning on the Xbox

**Comment by starkstrom-de** [comment]
@many7695 that's great to hear. I tried here and it's still failing, but with a slightly different error:
 
[04/11/2021, 15:51:42] [homebridge-xbox-tv] Error: 
    at Accessory.sendCharacteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1876:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1583:14)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7)
[04/11/2021, 15:51:45] [XboxTv] Device: 192.168.1.134 Xbox Series X, debug discoveryData: [].
[04/11/2021, 15:51:48] [XboxTv] Device: 192.168.1.134 Xbox Series X, set Power, error: {
  status: 'error_discovery',
  error: 'Console was not found on network. Probably failed'

So, still unable to find the xbox it seems :(
I should also note that, using the official xbox IOS App, I am able to turn on the console remotely, however, it does seem like it takes about 10 seconds or so. Is there a way to 'extend' the discovery or wait time to find the console to a little longer time to see if that makes it work?

**Comment by grzegorz914** [comment]
in 1.8.12-beta i have added possibility to set number of reties powerON, available in Advanced Settings.
Try set to 10 or so and check.

**Comment by starkstrom-de** [comment]
Thank you. I don't know how to install a beta, I will wait until you release this version and give that a try! 
I am not sure what/where advanced is, but I assume I can just add an entry in to the config file, right? what will the syntax be for the powerON retries?

**Comment by starkstrom-de** [comment]
Hey there, I just installed 18.15. Can you tell me how I would set the powerON retries please? I don't see a command in the config file, and also don't see it on the wiki.
 
You mentioned advanced settings, but I cannot find any documentation on where that is, and how to configure it.

**Comment by Fenibi** [comment]
Hi there, I just installed the last beta version 2.0.0-beta, in this version the power on and the power off feature don't work.
Also, I realize this library works: https://github.com/arcreative/xbox-on
Do you accept PRs? I could fix this bug this weekend.
Regards

**Comment by grzegorz914** [comment]
can you try 2.0.0 b477, here is working fine
<img width="1232" alt="Zrzut ekranu 2021-12-2 o 06 36 52" src="https://user-images.githubusercontent.com/28867813/144364161-6a6619fe-e1e6-4707-9bbb-e10f0bcc6c57.png">

**Comment by grzegorz914** [comment]
> Hey there, I just installed 18.15. Can you tell me how I would set the powerON retries please? I don't see a command in the config file, and also don't see it on the wiki.
> 
> You mentioned advanced settings, but I cannot find any documentation on where that is, and how to configure it.

I have don't  implemented this finally because lead to unexpected behavior and characteristics timeout, 
just please  try 2.0.0 beta, after install check your Xbox Live ID in settings and other properties

**Comment by grzegorz914** [comment]
Nice, if you see any bugs please reports here: #112

**Comment by djsomi** [comment]
Hi All,

Same issue here. Tried with latest stable and beta also. My console IP goes offline when it turned off. Series X. And there is no more Instant on mode, just Standby.
What can I do?

Many Thanks!

**Comment by grzegorz914** [comment]
@djsomi your problem hav nothing to do with this plugin. Check console settings, may be console software bug.

**Comment by djsomi** [comment]
> @djsomi your problem hav nothing to do with this plugin. Check console settings, may be console software bug.

Finally solved it, yesterday I've tested the new 2.0 stable, which started to work partially, so removed and reinstalled it again, and I just discovered that I've skipped to set the xboxLiveId at the prev config. 

Now its working fine, it can turn on even if the xbox is not pinging, + menus are working fine also. 
Thanks for this great plugin!

BR
Somi

**Comment by grzegorz914** [comment]
I have adde in readme Note about needed to set again xboxLiveId in settings: https://github.com/grzegorz914/homebridge-xbox-tv#note

**Comment by starkstrom-de** [comment]
I tried re-authorizing with the built-in authorization manager, but when
I reboot i get this:

 Device: 192.168.1.xxx Xbox Series X, Token request error: {
  status: 400,
  body: `{"error":"invalid_grant","error_description":"The provided
value for the 'code' parameter is not
valid.","correlation_id":"03d86417-e3c2-49e5-9ccf-3cd0a6d6ec69"}`

So now the Web API Token and Live ID are empty. 
And in the log it no longer shows the steps on how to manually set up /
authorize, so now I am dead in the water. 

If possible, please document the manual method in your wiki. Right now,
I have no idea how to do that, since it is not in the log.

Thanks!

-
Darrel


On December 26, 2021, Grzegorz ***@***.***> wrote:
> I have adde in readme Note about needed to set again xboxLiveId in
> settings: <https://github.com/grzegorz914/homebridge-xbox-tv#note>
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001133829>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7E6YX74DWWRM4SW6XJTUS3LIXANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by grzegorz914** [comment]
remove token using  authorization manager GUI and start authorization console again

**Comment by starkstrom-de** [comment]
Ahh yes ok. 
When I do that, I get this error in the new window:


We're unable to complete your request

invalid_request: The provided request must include a 'client_id' input
parameter.


-
Darrel


On December 27, 2021, Grzegorz ***@***.***> wrote:
> remove token using authorization manager GUI and start authorization
> console again
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001645140>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7E4HWKQAIKGYCIM3TCLUTCH3VANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by grzegorz914** [comment]
Are You set correct Live ID in settings

**Comment by grzegorz914** [comment]
fixed in 2.0.5, make update

**Comment by starkstrom-de** [comment]
Thanks, yep the console authorized successfully and the config file
seems to be correct again! 

Upon reboot, this error is now showing up in the log, just FYI. 

[27/12/2021, 08:48:59] [XboxTv] Device: 192.168.1.xxx Xbox Series X,
with liveId: , get Storage Devices error: {
  status: 400,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "MissingDeviceId",\r\n' +
    '    "errorMessage": "Missing DeviceId query parameter"\r\n' +
    '  },\r\n' +
    '  "deviceId": null,\r\n' +
    '  "result": [],\r\n' +
    '  "agentUserId": null\r\n' +
    '}'



-
Darrel


On December 27, 2021, Grzegorz ***@***.***> wrote:
> fixed in 2.0.5, make update
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001650491>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7E6BRADYVEAFLECY4BLUTCJSTANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by grzegorz914** [comment]
Can You post Your config here?

**Comment by starkstrom-de** [comment]
Sure:

            "devices": [
                {
                    "name": "Xbox Series X",
                    "host": "192.168.1.XXX",
                    "xboxliveid": "FD000xxxxxxxxxxx",
                    "xboxWebApiToken": "M.R3_BAY.191f749c-df30-6d55-
e5b3-81b80675fc8c",
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "webApiControl": true,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "rebootControl": false,
                    "getInputsFromDevice": true,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": true,
                    "inputs": [
                        {
                            "name": "Apple TV",
                            "reference":
"AppleInc.AppleTV_nzyj5cx40ttqa!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Dashboard",
                            "reference":
"Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                            "type": "HOME_SCREEN"
                        },
                        {
                            "name": "Amazon Music",
                            "reference":
"AmazonMobileLLC.AmazonMusicXbox_kc6t79cpj4tp0!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Plex",
                            "reference":
"CAF9E577.PlexforXbox_aam28m9va5cke!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Amazon Prime",
                            "reference":
"AmazonVideo.AmazonVideo_pwbj9vvecjh7j!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Netflix",
                            "reference":
"4DF9E0F8.Netflix_mcm4njqhnhss8!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "YouTubeTV",
                            "reference":
"GoogleInc.YouTubeTV_yfg5n0ztvskxp!App",
                            "type": "APPLICATION"
                        }
                    ],
                    "manufacturer": "Microsoft Corporation"
                }
            ],
            "platform": "XboxTv"

-
Darrel


On December 27, 2021, Grzegorz ***@***.***> wrote:
> Can You post Your config here?
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001654294>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7E5RFUGBBJLD64UYGJ3UTCK4VANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by grzegorz914** [comment]
ab version v2.0.0 and above correct properties is xboxLiveId not xboxliveid, please always use guy to configure or look in readme or sample config.

**Comment by starkstrom-de** [comment]
thank you, sorry for this Pain...now that the ID syntax is correct, get
different error:

[27/12/2021, 09:43:25] [XboxTv] Device: 192.168.1.XXX Xbox Series X,
authorized and Web Api enabled.
[27/12/2021, 09:43:25] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge 6249)
is running on port 51036.
[27/12/2021, 09:43:25] Xbox Series X 01F5 is running on port 35997.
[27/12/2021, 09:43:25] Please add [Xbox Series X 01F5] manually in Home
app. Setup Code: 818-38-615
[27/12/2021, 09:43:25] [XboxTv] Device: 192.168.1.XXX Xbox Series X,
with liveId: FD000XXXXXXXX, get Installed Apps error: {
  status: 404,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "XboxDataNotFound",\r\n' +
    '    "errorMessage": "Xbox not found for user:
0003BFFD88C32D7A"\r\n' +
    '  },\r\n' +
    '  "result": [],\r\n' +
    '  "agentUserId": null\r\n' +
    '}'
}.

I have verified that the LiveID is correct. I am not sure where the
"user: 0003BFFD88C32D7A" is coming from? I don't see that in any
configs. 

-
Darrel


On December 27, 2021, Grzegorz ***@***.***> wrote:
> ab version v2.0.0 and above correct properties is xboxLiveId not
> xboxliveid, please always use guy to configure or look in readme or
> sample config.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001660991>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7E4UWDGDDPC3E7CPUXLUTCMWZANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by grzegorz914** [comment]
Are You authorized console with correct Live ID?, I think You make this without Live ID, if not please authorize it again from GUI. First Clear Web Api Token.

**Comment by starkstrom-de** [comment]
i can do that. I feel maybe that i just should uninstall and start over.
Should I manually delete the tokenfile in the folder as well? If yes,
which is the token file? There are several files with the word token in
them. ApiToken files and authToken files. I have several for both. Are
these of concern and should be deleted?

-
Darrel


On December 27, 2021, Grzegorz ***@***.***> wrote:
> Are You authorized console with correct Live ID?, I think You make
> this without Live ID, if not please authorize it again from GUI. First
> Clear Web Api Token.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001687864>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7E3C4HCRKDUQQOMDM4LUTCU2NANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by grzegorz914** [comment]
Yes, You can manually delete it in folder, file authToken_xxxxx

**Comment by starkstrom-de** [comment]
Ohhh man... :(
I removed the plug-in, deleted the xboxtv folder as you said.
I re-installed, and the xbox authorized successfully with my liveid.
Upon reboot, I now get these:

[27/12/2021, 10:43:44] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge 6249)
is running on port 51036.
[27/12/2021, 10:43:44] [XboxTv] Device: 192.168.1.150 Xbox Series X,
prepareInformationService error: SyntaxError: Unexpected end of JSON
input
    at JSON.parse (<anonymous>)
    at xboxTvDevice.prepareAccessory
(/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:741:54)
[27/12/2021, 10:43:44] Xbox Series X 01F5 is running on port 44959.
[27/12/2021, 10:43:44] Please add [Xbox Series X 01F5] manually in Home
app. Setup Code: 818-38-615
[27/12/2021, 10:43:46] [XboxTv] Device: 192.168.1.150 Xbox Series X,
authorized and Web Api enabled.
[27/12/2021, 10:43:46] [XboxTv] Device: 192.168.1.150 Xbox Series X, get
Power state successful: OFF
[27/12/2021, 10:43:46] [XboxTv] Device: 192.168.1.150 Xbox Series X, get
Input successful, input: Screensaver, reference:
Xbox.IdleScreen_8wekyb3d8bbwe!Xbox.IdleScreen.Application, product Id:
Screensaver
[27/12/2021, 10:43:46] [XboxTv] Device: 192.168.1.150 Xbox Series X, get
Current Media state successful: STOP
[27/12/2021, 10:43:46] [XboxTv] Device: 192.168.1.150 Xbox Series X, get
Target Media state successful: STOP
[27/12/2021, 10:43:46] [XboxTv] Device: 192.168.1.150 Xbox Series X, get
Mute successful: OFF
[27/12/2021, 10:43:46] [XboxTv] Device: 192.168.1.150 Xbox Series X, get
Volume successful: 0
[27/12/2021, 10:43:47] [XboxTv] Device: 192.168.1.150 Xbox Series X,
with liveId: FD000DB6B85ACE04, get Installed Apps error: {
  status: 404,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "XboxDataNotFound",\r\n' +
    '    "errorMessage": "Xbox not found for user:
0003BFFD88C32D7A"\r\n' +
    '  },\r\n' +
    '  "result": [],\r\n' +
    '  "agentUserId": null\r\n' +
    '}'
}.

The config.json is now pristine, since I started over:

"devices": [
                {
                    "name": "Xbox Series X",
                    "host": "192.168.1.150",
                    "xboxLiveId": "FD000XX",
                    "clientId": "5e5ead27-ed60-482d-b3fc-702b28a97404",
                    "disableLogInfo": false,
                    "webApiControl": true,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "getInputsFromDevice": true,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": false,
                    "enableDebugMode": false,
                    "xboxWebApiToken": "M.R3_BAY.81d967a4-e9b7-d5d1-
5552-9cfea0a4b3a7"
                }

-
Darrel


On December 27, 2021, Grzegorz ***@***.***> wrote:
> Yes, You can manually delete it in folder, file authToken_xxxxx
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001690155>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7E6TUROIF5Z4NU3MBBTUTCVRBANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>

**Comment by grzegorz914** [comment]
Mays be You console is lined to other Xbox Live Account, the error took that data of the console is not found on this Xbox Live Account. Log In using web browser to your Xbox Live Account and check ob this console is there.

**Comment by starkstrom-de** [comment]
I checked. It's there, it's the only one i have :( 

Oh well. Thank you for all your help!


-
Darrel


On December 27, 2021, Grzegorz ***@***.***> wrote:
> Mays be You console is lined to other Xbox Live Account, the error
> took that data of the console is not found on this Xbox Live Account.
> Log In using web browser to your Xbox Live Account and check ob this
> console is there.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/grzegorz914/homebridge-xbox-
tv/issues/106#issuecomment-1001702273>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AWKH7EYPYHQVREPMHTTLUPLUTCZZ3ANCNFSM5HHLHKYA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you authored the thread.Message ID:
***@***.***>
