### ISSUE TITLE
Unable to switch Inputs

### ISSUE THREAD

**Issue by timjrusn** [grzegorz914/homebridge-xbox-tv#108]
I have my apps configured correctly. When I use my Xbox controller to choose the app i.e. YouTube. In HomeKit and HomeBridge is shows that is the application that I am on. If I use the HomeKit input to change it to the dashboard my Xbox does not respond. Also, it does not respond to power on. I get the message in HomeBridge Log Xbox disconnect. My settings are correct. Under Sleep Mode & Startup I have Sleep Mode on Standby. In Remote Features under Xbox App Preferences I have Allow Connections from any Device. Console Settings Power: Instant ON, Nat Type: Open, When the console is on I am able to ping it. I have the console hardwired. I have homebridge on a Microsoft Server that is hardwired as well.

[11/7/2021, 1:15:11 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, get Power state successful: OFF
[11/7/2021, 1:15:13 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug discoveryData: [].
[11/7/2021, 1:15:18 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug discoveryData: [].
[11/7/2021, 1:15:19 AM] [homebridge-xbox-tv] Error: 
    at Accessory.sendCharacteristicWarning (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:1876:14)
    at Timeout._onTimeout (C:\Users\Administrator\AppData\Roaming\npm\node_modules\homebridge\node_modules\hap-nodejs\src\lib\Accessory.ts:1583:14)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
[11/7/2021, 1:15:23 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug discoveryData: [].
[11/7/2021, 1:15:24 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, set Power, error: {
  status: 'error_discovery',
  error: 'Console was not found on network. Probably failed'
}
[11/7/2021, 1:15:28 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug discoveryData: [].
[11/7/2021, 1:15:33 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug discoveryData: [].
[11/7/2021, 1:15:38 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug discoveryData: [].
[11/7/2021, 1:15:43 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug discoveryData: [].

**Comment by timjrusn** [comment]
This is the log after I used my controller to turn on the xbox.


[11/7/2021, 1:16:37 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, Connected.
[11/7/2021, 1:16:37 AM] [XboxTv] -------- Xbox One X --------
[11/7/2021, 1:16:37 AM] [XboxTv] Manufacturer: Microsoft
[11/7/2021, 1:16:37 AM] [XboxTv] Model: Xbox One X
[11/7/2021, 1:16:37 AM] [XboxTv] Serialnr: FD00FF016B1A31E9
[11/7/2021, 1:16:37 AM] [XboxTv] Firmware: 10.0.22000
[11/7/2021, 1:16:37 AM] [XboxTv] ----------------------------------
[11/7/2021, 1:16:37 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug update device state.
[11/7/2021, 1:16:37 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug writeDevInfo: {
  "manufacturer": "Microsoft",
  "modelName": "Xbox One X",
  "serialNumber": "FD00FF016B1A31E9",
  "firmwareRevision": "10.0.22000"
}
[11/7/2021, 1:16:40 AM] [XboxTv] Device 10.0.0.250 Xbox One X, debug _on_console_status message: {
  live_tv_provider: 0,
  major_version: 10,
  minor_version: 0,
  build_number: 22000,
  locale: 'en-US',
  apps: [Array]
}, xbox: {
  _ip: '10.0.0.250',
  _certificate: <Buffer 30 82 02 48 30 82 01 30 a0 03 02 01 02 02 11 00 99 6b 30 a0 6f b5 ce 4e a7 6d 89 e2 3d 98 ae cd 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 25 31 ... 538 more bytes>,
  _iv: false,
  _liveid: 'FD00FF016B1A31E9',
  _is_authenticated: false,
  _participantid: 2,
  _connection_status: false,
  _request_num: 10,
  _target_participant_id: 0,
  _source_participant_id: 2,
  _fragments: {},
  _crypto: [Object],
  getIp: [Function: getIp],
  getCertificate: [Function: getCertificate],
  getLiveid: [Function: getLiveid],
  setLiveid: [Function: setLiveid],
  get_requestnum: [Function: get_requestnum],
  set_participantid: [Function: set_participantid],
  connect: [Function: connect],
  loadCrypto: [Function: loadCrypto]
}, remote: { address: '10.0.0.250', family: 'IPv4', port: 5050, size: 186 }, {
  _client_id: 368,
  _console: [Object],
  _socket: [Socket],
  _events: [EventEmitter],
  _last_received_time: 1636262200,
  _is_broadcast: false,
  _ip: '10.0.0.250',
  _interval_timeout: Timeout {
    _idleTimeout: 1000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 233484,
    _onTimeout: [Function: bound ],
    _timerArgs: undefined,
    _repeat: 1000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 16252,
    [Symbol(triggerId)]: 16247
  },
  _managers: [Object],
  _managers_num: 3,
  _connection_status: true,
  _current_app: 'Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application',
  discovery: [Function: discovery],
  getActiveApp: [Function: getActiveApp],
  isConnected: [Function: isConnected],
  powerOn: [Function: powerOn],
  powerOff: [Function: powerOff],
  connect: [Function: connect],
  on: [Function: on],
  disconnect: [Function: disconnect],
  recordGameDvr: [Function: recordGameDvr],
  addManager: [Function: addManager],
  getManager: [Function: getManager],
  _getSocket: [Function: _getSocket],
  _closeClient: [Function: _closeClient],
  _send: [Function: _send]
}
[11/7/2021, 1:16:40 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug mediaStateData: { title_id: 0 }
[11/7/2021, 1:16:40 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug update device state.
[11/7/2021, 1:16:44 AM] [XboxTv] Device 10.0.0.250 Xbox One X, debug _on_console_status message: {
  live_tv_provider: 0,
  major_version: 10,
  minor_version: 0,
  build_number: 22000,
  locale: 'en-US',
  apps: [Array]
}, xbox: {
  _ip: '10.0.0.250',
  _certificate: <Buffer 30 82 02 48 30 82 01 30 a0 03 02 01 02 02 11 00 99 6b 30 a0 6f b5 ce 4e a7 6d 89 e2 3d 98 ae cd 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 25 31 ... 538 more bytes>,
  _iv: false,
  _liveid: 'FD00FF016B1A31E9',
  _is_authenticated: false,
  _participantid: 2,
  _connection_status: false,
  _request_num: 12,
  _target_participant_id: 0,
  _source_participant_id: 2,
  _fragments: {},
  _crypto: [Object],
  getIp: [Function: getIp],
  getCertificate: [Function: getCertificate],
  getLiveid: [Function: getLiveid],
  setLiveid: [Function: setLiveid],
  get_requestnum: [Function: get_requestnum],
  set_participantid: [Function: set_participantid],
  connect: [Function: connect],
  loadCrypto: [Function: loadCrypto]
}, remote: { address: '10.0.0.250', family: 'IPv4', port: 5050, size: 186 }, {
  _client_id: 368,
  _console: [Object],
  _socket: [Socket],
  _events: [EventEmitter],
  _last_received_time: 1636262204,
  _is_broadcast: false,
  _ip: '10.0.0.250',
  _interval_timeout: Timeout {
    _idleTimeout: 1000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 237484,
    _onTimeout: [Function: bound ],
    _timerArgs: undefined,
    _repeat: 1000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 16252,
    [Symbol(triggerId)]: 16247
  },
  _managers: [Object],
  _managers_num: 3,
  _connection_status: true,
  _current_app: 'Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application',
  discovery: [Function: discovery],
  getActiveApp: [Function: getActiveApp],
  isConnected: [Function: isConnected],
  powerOn: [Function: powerOn],
  powerOff: [Function: powerOff],
  connect: [Function: connect],
  on: [Function: on],
  disconnect: [Function: disconnect],
  recordGameDvr: [Function: recordGameDvr],
  addManager: [Function: addManager],
  getManager: [Function: getManager],
  _getSocket: [Function: _getSocket],
  _closeClient: [Function: _closeClient],
  _send: [Function: _send]
}
[11/7/2021, 1:16:44 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug mediaStateData: { title_id: 0 }
[11/7/2021, 1:16:44 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug update device state.

**Comment by timjrusn** [comment]
ndefined
[11/7/2021, 1:18:14 AM] [XboxTv] Device 10.0.0.250 Xbox One X, debug _on_console_status message: {
  live_tv_provider: 0,
  major_version: 10,
  minor_version: 0,
  build_number: 22000,
  locale: 'en-US',
  apps: [Array]
}, xbox: {
  _ip: '10.0.0.250',
  _certificate: <Buffer 30 82 02 48 30 82 01 30 a0 03 02 01 02 02 11 00 99 6b 30 a0 6f b5 ce 4e a7 6d 89 e2 3d 98 ae cd 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 25 31 ... 538 more bytes>,
  _iv: false,
  _liveid: 'FD00FF016B1A31E9',
  _is_authenticated: false,
  _participantid: 2,
  _connection_status: false,
  _request_num: 42,
  _target_participant_id: 0,
  _source_participant_id: 2,
  _fragments: {},
  _crypto: [Object],
  getIp: [Function: getIp],
  getCertificate: [Function: getCertificate],
  getLiveid: [Function: getLiveid],
  setLiveid: [Function: setLiveid],
  get_requestnum: [Function: get_requestnum],
  set_participantid: [Function: set_participantid],
  connect: [Function: connect],
  loadCrypto: [Function: loadCrypto]
}, remote: { address: '10.0.0.250', family: 'IPv4', port: 5050, size: 186 }, {
  _client_id: 368,
  _console: [Object],
  _socket: [Socket],
  _events: [EventEmitter],
  _last_received_time: 1636262294,
  _is_broadcast: false,
  _ip: '10.0.0.250',
  _interval_timeout: Timeout {
    _idleTimeout: 1000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 327606,
    _onTimeout: [Function: bound ],
    _timerArgs: undefined,
    _repeat: 1000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 16252,
    [Symbol(triggerId)]: 16247
  },
  _managers: [Object],
  _managers_num: 3,
  _connection_status: true,
  _current_app: 'Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application',
  discovery: [Function: discovery],
  getActiveApp: [Function: getActiveApp],
  isConnected: [Function: isConnected],
  powerOn: [Function: powerOn],
  powerOff: [Function: powerOff],
  connect: [Function: connect],
  on: [Function: on],
  disconnect: [Function: disconnect],
  recordGameDvr: [Function: recordGameDvr],
  addManager: [Function: addManager],
  getManager: [Function: getManager],
  _getSocket: [Function: _getSocket],
  _closeClient: [Function: _closeClient],
  _send: [Function: _send]
}
[11/7/2021, 1:18:14 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug mediaStateData: { title_id: 0 }
[11/7/2021, 1:18:14 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug update device state.
[11/7/2021, 1:18:44 AM] [XboxTv] Device 10.0.0.250 Xbox One X, debug _on_console_status message: {
  live_tv_provider: 0,
  major_version: 10,
  minor_version: 0,
  build_number: 22000,
  locale: 'en-US',
  apps: [Array]
}, xbox: {
  _ip: '10.0.0.250',
  _certificate: <Buffer 30 82 02 48 30 82 01 30 a0 03 02 01 02 02 11 00 99 6b 30 a0 6f b5 ce 4e a7 6d 89 e2 3d 98 ae cd 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 25 31 ... 538 more bytes>,
  _iv: false,
  _liveid: 'FD00FF016B1A31E9',
  _is_authenticated: false,
  _participantid: 2,
  _connection_status: false,
  _request_num: 52,
  _target_participant_id: 0,
  _source_participant_id: 2,
  _fragments: {},
  _crypto: [Object],
  getIp: [Function: getIp],
  getCertificate: [Function: getCertificate],
  getLiveid: [Function: getLiveid],
  setLiveid: [Function: setLiveid],
  get_requestnum: [Function: get_requestnum],
  set_participantid: [Function: set_participantid],
  connect: [Function: connect],
  loadCrypto: [Function: loadCrypto]
}, remote: { address: '10.0.0.250', family: 'IPv4', port: 5050, size: 186 }, {
  _client_id: 368,
  _console: [Object],
  _socket: [Socket],
  _events: [EventEmitter],
  _last_received_time: 1636262324,
  _is_broadcast: false,
  _ip: '10.0.0.250',
  _interval_timeout: Timeout {
    _idleTimeout: 1000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 357621,
    _onTimeout: [Function: bound ],
    _timerArgs: undefined,
    _repeat: 1000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 16252,
    [Symbol(triggerId)]: 16247
  },
  _managers: [Object],
  _managers_num: 3,
  _connection_status: true,
  _current_app: 'Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application',
  discovery: [Function: discovery],
  getActiveApp: [Function: getActiveApp],
  isConnected: [Function: isConnected],
  powerOn: [Function: powerOn],
  powerOff: [Function: powerOff],
  connect: [Function: connect],
  on: [Function: on],
  disconnect: [Function: disconnect],
  recordGameDvr: [Function: recordGameDvr],
  addManager: [Function: addManager],
  getManager: [Function: getManager],
  _getSocket: [Function: _getSocket],
  _closeClient: [Function: _closeClient],
  _send: [Function: _send]
}
[11/7/2021, 1:18:44 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug mediaStateData: { title_id: 0 }
[11/7/2021, 1:18:44 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug update device state.
[11/7/2021, 1:19:14 AM] [XboxTv] Device 10.0.0.250 Xbox One X, debug _on_console_status message: {
  live_tv_provider: 0,
  major_version: 10,
  minor_version: 0,
  build_number: 22000,
  locale: 'en-US',
  apps: [Array]
}, xbox: {
  _ip: '10.0.0.250',
  _certificate: <Buffer 30 82 02 48 30 82 01 30 a0 03 02 01 02 02 11 00 99 6b 30 a0 6f b5 ce 4e a7 6d 89 e2 3d 98 ae cd 30 0d 06 09 2a 86 48 86 f7 0d 01 01 0b 05 00 30 25 31 ... 538 more bytes>,
  _iv: false,
  _liveid: 'FD00FF016B1A31E9',
  _is_authenticated: false,
  _participantid: 2,
  _connection_status: false,
  _request_num: 62,
  _target_participant_id: 0,
  _source_participant_id: 2,
  _fragments: {},
  _crypto: [Object],
  getIp: [Function: getIp],
  getCertificate: [Function: getCertificate],
  getLiveid: [Function: getLiveid],
  setLiveid: [Function: setLiveid],
  get_requestnum: [Function: get_requestnum],
  set_participantid: [Function: set_participantid],
  connect: [Function: connect],
  loadCrypto: [Function: loadCrypto]
}, remote: { address: '10.0.0.250', family: 'IPv4', port: 5050, size: 186 }, {
  _client_id: 368,
  _console: [Object],
  _socket: [Socket],
  _events: [EventEmitter],
  _last_received_time: 1636262354,
  _is_broadcast: false,
  _ip: '10.0.0.250',
  _interval_timeout: Timeout {
    _idleTimeout: 1000,
    _idlePrev: [TimersList],
    _idleNext: [TimersList],
    _idleStart: 387636,
    _onTimeout: [Function: bound ],
    _timerArgs: undefined,
    _repeat: 1000,
    _destroyed: false,
    [Symbol(refed)]: true,
    [Symbol(kHasPrimitive)]: false,
    [Symbol(asyncId)]: 16252,
    [Symbol(triggerId)]: 16247
  },
  _managers: [Object],
  _managers_num: 3,
  _connection_status: true,
  _current_app: 'Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application',
  discovery: [Function: discovery],
  getActiveApp: [Function: getActiveApp],
  isConnected: [Function: isConnected],
  powerOn: [Function: powerOn],
  powerOff: [Function: powerOff],
  connect: [Function: connect],
  on: [Function: on],
  disconnect: [Function: disconnect],
  recordGameDvr: [Function: recordGameDvr],
  addManager: [Function: addManager],
  getManager: [Function: getManager],
  _getSocket: [Function: _getSocket],
  _closeClient: [Function: _closeClient],
  _send: [Function: _send]
}
[11/7/2021, 1:19:14 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug mediaStateData: { title_id: 0 }
[11/7/2021, 1:19:14 AM] [XboxTv] Device: 10.0.0.250 Xbox One X, debug update device state.

This says it worked, but my xbox says otherwise. Sorry for the multiple comments. Just making sure you have everything when you see this and if I am not up.

**Comment by grzegorz914** [comment]
Are You enable web Api control?, switch inputs is possible only if web Api is enabled and console authenticated.?

**Comment by timjrusn** [comment]
I wasn't successful to get it to work

**Comment by grzegorz914** [comment]
Without authorization the console switch input is not possible.
