### ISSUE TITLE
getInputsFromDevice Not working

### ISSUE THREAD

**Issue by RobotLimeLtd** [grzegorz914/homebridge-xbox-tv#109]
I’ve got this set up and authorised via my Microsoft account, but I also have getInputsFromDevice Set to “true”, yet it’s not picking up the apps I launch on the Xbox Series X.  The logs show when I go back to the dashboard, but they don’t show anything when I launch an app.

Have I misunderstood this feature?

**Comment by grzegorz914** [comment]
Try restart plugin itself.

**Comment by tecdude** [comment]
I restart plugin, server and Xbox over and over and that doesn't work. I have passwords for access to personal data on Xbox, should this be removed?

**Comment by grzegorz914** [comment]
No, this have nothing to do, Please enable debug mode, restart pligin and get the complete log.

**Comment by grzegorz914** [comment]
I close this as no response from user.
