### ISSUE TITLE
Where can I find the reference for games and apps on for adding inputs?

### ISSUE THREAD

**Issue by YTF1shhh** [grzegorz914/homebridge-xbox-tv#119]
I figured out that the "oneStoreProductId" can be found in the link of the app or game on Microsoft.com but where is the "reference" I found the reference for the City Skylines game by googling it and it brought me to a random website that seemed to have info for City Skylines and only City Skylines.

**Comment by YTF1shhh** [comment]
I figured that out by looking at closed issues, now I'm having another issue, When I change inputs in Homekit it doesn't do anything, When I open an app I have added to the config it changes the status to that app in Homekit.
my code
I have Web API enabled 
Here is the log when I change inputs in HomeKit, it doesn't do anything in my Xbox.
"inputs": [
                        {
                            "name": "Spotify",
                            "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App"
                        },
                        {
                            "name": "YouTube",
                            "reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App"
                        },
                        {
                            "name": "Netflix",
                            "reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App"
                        },
                        {
                            "name": "Microsoft Edge",
                            "reference": "Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"
                        },
                        {
                            "name": "Disney",
                            "reference": "Disney.37853FC22B2CE_6rarf9sa4v8jt!App"
                        }

**Comment by grzegorz914** [comment]
Homebridge log if switch to that input or in stored file if web api enabled, all is in the readme descriebed
