### ISSUE TITLE
When I change inputs in Homekit it doesn't do anything

### ISSUE THREAD

**Issue by YTF1shhh** [grzegorz914/homebridge-xbox-tv#120]
When I open an app I have added to the config it changes the status to that app in Homekit.
my code
I have Web API enabled
Here is the log when I change inputs in HomeKit, it doesn't do anything in my Xbox.
"inputs": [
{
"name": "Spotify",
"reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App"
},
{
"name": "YouTube",
"reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App"
},
{
"name": "Netflix",
"reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App"
},
{
"name": "Microsoft Edge",
"reference": "Microsoft.MicrosoftEdge_8wekyb3d8bbwe!MicrosoftEdge"
},
{
"name": "Disney",
"reference": "Disney.37853FC22B2CE_6rarf9sa4v8jt!App"
}

**Comment by grzegorz914** [comment]
Here is all described, https://github.com/grzegorz914/homebridge-xbox-tv#configuration
To switch app You need set oneStoreProductId and Web Api enable
