### ISSUE TITLE
Get Storage Devices Error on fresh plugin setup

### ISSUE THREAD

**Issue by adammodlin** [grzegorz914/homebridge-xbox-tv#121]
This is on v1.8.15 with a Xbox Series X. Let me know if you'd like me to investigate anything else.

```
[18/12/2021, 13:12:13] [homebridge-xbox-tv] Device: 192.168.1.196 Xbox Series X, with liveid: , get Storage Devices error: {
  status: 400,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "MissingDeviceId",\r\n' +
    '    "errorMessage": "Missing DeviceId query parameter"\r\n' +
    '  },\r\n' +
    '  "deviceId": null,\r\n' +
    '  "result": [],\r\n' +
    '  "agentUserId": null\r\n' +
    '}'
}.
```

**Comment by adammodlin** [comment]
This looks like it's because the guided setup did not populate the Xbox network device ID (live ID in config). Once I populate it manually, it works. I'll take a look and see if I can figure out why it wasn't set.

**Comment by grzegorz914** [comment]
Here is all described 
https://github.com/grzegorz914/homebridge-xbox-tv#configuration
