### ISSUE TITLE
Switches

### ISSUE THREAD

**Issue by tecdude** [grzegorz914/homebridge-xbox-tv#125]
Could the buttons be buttons in HK or the of/off be a switch, so they fit in together better?

**Comment by grzegorz914** [comment]
I don’t understood what you mean. Can you be more specific?

**Comment by tecdude** [comment]
The On/Off switch is a button, but 'Buttons' added by Homebridge appear as switches (below). Is it possible to make the 'buttons' appear as buttons in HomeKit, or the on/off switch be made a switch in HomeKit, so they match?
![Screenshot 2021-12-27 at 13 51 34](https://user-images.githubusercontent.com/92227828/147478030-c95da0b8-2094-4001-b645-d37b9c124e4e.png)
.

**Comment by grzegorz914** [comment]
OK, update to 2.0.2 and let me know.

**Comment by tecdude** [comment]
Still appears as a switch, how can I update to the typo fix?
