### ISSUE TITLE
Unexpected boot up after shutdown

### ISSUE THREAD

**Issue by many7695** [grzegorz914/homebridge-xbox-tv#127]
Im currently using 2.0.6 update when I say Siri or my  Homebridge site it turns  off my Xbox but  5 seconds later my Xbox turns back on

It might not be a issue with this when I say ok google turn of Xbox it does the same my Xbox turns back 5 seconds later, anybody else getting this

**Comment by grzegorz914** [comment]
can You try 2.0.9-beta.1 and let me know

**Comment by grzegorz914** [comment]
I have also observed this behavior sometimes but only on device connected to WiFi, other console connected to LAN always working correct.

**Comment by grzegorz914** [comment]
Still this issue with latest release?

**Comment by grzegorz914** [comment]
no answer, I close this
