### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by siddrajput** [grzegorz914/homebridge-xbox-tv#128]
After pushing "AUTHORIZE CONSOLE", the webpage tries to open:

http://localhost:8080/auth/callback?code=M.R3_BL2.f06aebde-4377-cf17-5f56-4cdc34fe0b91

But result is:

This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

**Comment by grzegorz914** [comment]
Read care fully and go step by step:
https://github.com/grzegorz914/homebridge-xbox-tv#authorization-manager

**Comment by siddrajput** [comment]
I did. Anyway, I got it working. The XBOX wasn't showing up in my iPhone's Home app because it was in the "Home" tab, not in the "Rooms" tab.

**Comment by grzegorz914** [comment]
The accessory will always added to the Home screen, not to the rooms.

**Comment by LordZork** [comment]
I've tried numerous times to submit a new issue, but I keep getting an error.  So, I will post my issue here as it appears similar to this one...

@siddrajput, were you ever able to get your xbox authorized?  If so, can you tell me what you did?

@grzegorz914, I run Homebridge on a Raspberry Pi via the [Official Homebridge Raspberry Pi Image](https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started).  This means Homebridge is not installed on an actual OS, which also means I manage Homebridge via a web interface from a separate computer.

That said, I have tried to authorize my Xbox via three different web browsers, from both my Mac and my iPhone.  Also, I have ensured there are no pop-up blockers.  Regardless, I keep running into the following problem...

> Unable to connect / can’t establish a connection to the server at localhost:8080.

Also, the Homebridge Logs show the following error...

`[homebridge-xbox-tv] Device: ###.###.#.## Xbox Series X, not authorized, please use Authorization Manager.`

I am guessing this is a result of running the authorization process from a separate computer (not the computer Homebridge is running on).  If so, is this something you can fix, or do you have any ideas for a workaround?

I ran into a similar issue with another plugin, [here](https://github.com/dhleong/playactor/issues/23), and the developer was able to fix it by making it possible to authorize remotely from a separate computer.

However, If that isn't the issue, do you have any idea what might be the problem?

Thanks!

**Comment by grzegorz914** [comment]
Can you record video of the complete process you tried?

**Comment by LordZork** [comment]
@grzegorz914, thanks for the quick reply!  For security reasons, I'd rather not record a video of the process.  However, I can (and have) taken screenshots of every step, which I have included below.

### Setup and Authorization Steps...
![HB XBTV 01](https://user-images.githubusercontent.com/65878888/194616318-a0c16b7c-6cdc-42fe-b99b-09377bb770fb.png)
![HB XBTV 02](https://user-images.githubusercontent.com/65878888/194616322-679f9d7f-a5f5-4cc2-b2c5-651856a3316e.png)
![HB XBTV 03](https://user-images.githubusercontent.com/65878888/194616326-4fa7368f-77a1-49a3-a22f-47a4d7c29d79.png)
![HB XBTV 04](https://user-images.githubusercontent.com/65878888/194616327-5f6fe3d7-4fe8-4e3c-acd4-8eaee92bebe4.png)
![HB XBTV 05](https://user-images.githubusercontent.com/65878888/194616330-21bb5eea-c567-4a16-8fe9-72db30311c9d.png)
![HB XBTV 06](https://user-images.githubusercontent.com/65878888/194616331-de6d848f-d356-48f6-b794-c8d8f6cce2a1.png)
![HB XBTV 07](https://user-images.githubusercontent.com/65878888/194616332-5f28eaba-b6de-4031-b89c-2f7cf417d2ad.png)
![HB XBTV 08](https://user-images.githubusercontent.com/65878888/194616334-d47280d0-7476-4b2a-a25f-b4b00a52d11b.png)
![HB XBTV 09](https://user-images.githubusercontent.com/65878888/194616336-1564375f-613c-4a9a-9d82-569bebffd7a3.png)
![HB XBTV 10](https://user-images.githubusercontent.com/65878888/194616338-4671375a-18e8-4128-b569-15f36b7e306a.png)
![HB XBTV 11](https://user-images.githubusercontent.com/65878888/194616339-e27cf5f3-c9e4-43a5-8068-66341acd8d4b.png)

### Homebridge Logs...
`[homebridge-xbox-tv] Device: ###.###.#.## Xbox Series X, not authorized, please use Authorization Manager.`

Thanks in advance for any help you can provide!

**Comment by grzegorz914** [comment]
Are You press save api token on last screen?

**Comment by LordZork** [comment]
@grzegorz914, yes, and I just ran through the whole setup again just to make sure. Still the same issue.

What is supposed to happen after clicking "Continue" on this page?...
![HB XBTV 08](https://user-images.githubusercontent.com/65878888/194624363-e18c3b76-87c6-4efa-b9a7-679e511e323d.png)

I'm guessing this (below) is not what is supposed to happen (though, there is a code in the address field, which I copy and paste into the "Web Api Token" field)?...

![HB XBTV 09](https://user-images.githubusercontent.com/65878888/194624619-0fea75c9-7ee8-4911-8ff5-95de0a6c6d75.png)

**Comment by grzegorz914** [comment]
What are You put in to Live ID?
look also in /var/lib/homebridge/xboxtv/authtoken_xxxxxx file

**Comment by grzegorz914** [comment]
Also I don't see on your screenshot  after press "save web api token" info "Web Api Token Saved"

**Comment by LordZork** [comment]
@grzegorz914,

My Live ID is redacted (blacked out) in the screenshots for security reasons, but I did add my Live ID (found in my console settings), which looks like: FXXXXXXXXXXXXXXX.

Also, I am able to add my Xbox to the Home app, and I can turn it on and off.  I just can't use the extra features that require the authorization.

After I click on "save web api token" I also click on the other "save" button for the configuration screen.  Then I restart Homebridge.  Also, the api token that I copy from the browser address field is added to the Config.

I will try again and see if I can find the homebridge log during he authorization process.

**Comment by grzegorz914** [comment]
After "save web api token" need to be displayed  info "Web Api Token Saved", are you see this?

**Comment by LordZork** [comment]
Here's the missing screenshot that shows that the token (that I copied and pasted) was saved...

![HB XBTV 12](https://user-images.githubusercontent.com/65878888/194642052-2314d49e-4807-4a3d-a767-b7e3ad5b45c3.png)

**Comment by LordZork** [comment]
@grzegorz914, here is the log...

```
[07/10/2022, 14:41:32] [Homebridge UI] Terminal session ended.
[07/10/2022, 14:41:41] [Homebridge UI] Running Command: sudo -E -n npm install -g homebridge-xbox-tv@2.3.6
[07/10/2022, 14:42:26] [Homebridge UI] Starting terminal session
[07/10/2022, 14:42:27] [Homebridge UI] Terminal session ended.
[07/10/2022, 14:42:46] [Homebridge UI] Changes to config.json saved.
[07/10/2022, 14:42:46] [Homebridge UI] [homebridge-xbox-tv] Terminating child process...
[07/10/2022, 14:42:46] [Homebridge UI] [homebridge-xbox-tv] Child process ended
[07/10/2022, 14:43:00] [Homebridge UI] Changes to config.json saved.
[07/10/2022, 14:43:22] [Homebridge UI] [homebridge-xbox-tv] Incoming Request: /clearToken
[07/10/2022, 14:43:22] [Homebridge UI] Changes to config.json saved.
[07/10/2022, 14:43:26] [Homebridge UI] [homebridge-xbox-tv] Incoming Request: /startAuthorization
HEARTBEAT PING {}
HEARTBEAT sending PONG { last_stream_id_received: 2 }
[07/10/2022, 14:43:58] [Homebridge UI] Changes to config.json saved.
[07/10/2022, 14:44:19] [Homebridge UI] Changes to config.json saved.
[07/10/2022, 14:44:19] [Homebridge UI] [homebridge-xbox-tv] Terminating child process...
[07/10/2022, 14:44:20] [Homebridge UI] [homebridge-xbox-tv] Child process ended
[07/10/2022, 14:44:28] [Homebridge UI] Homebridge restart request received
[07/10/2022, 14:44:28] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[07/10/2022, 14:44:28] [Homebridge UI] Sending SIGTERM to Homebridge
[07/10/2022, 14:44:28] Got SIGTERM, shutting down Homebridge...
```
I still get this error...

`[07/10/2022, 14:44:48] [homebridge-xbox-tv] Device: ###.###.#.## Xbox Series X, not authorized, please use Authorization Manager.`

**Comment by LordZork** [comment]
@grzegorz914, is it possible the issue is what I originally mentioned?...

### Homebridge Setup...
I run Homebridge on a Raspberry Pi via the [Official Homebridge Raspberry Pi Image](https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started). This means Homebridge is not installed on an actual OS, which also means I manage Homebridge via a web interface from a separate computer.

### Possible Issue?...
I am guessing this is a result of running the authorization process from a separate computer (not the computer Homebridge is running on). I ran into a similar issue with another plugin, [here](https://github.com/dhleong/playactor/issues/23), and the developer was able to fix it by making it possible to authorize remotely from a separate computer.

### What is supposed to happen?...

After clicking "Continue" on the Microsoft page, Is it supposed to return an "unable to connect to localhost" page?  If not, what is supposed to happen?

**Comment by grzegorz914** [comment]
No, its No matter from which computer You start authorization. All is correct here, I think the token file is not saved, please lock in to the /var/lib/Homebridge/xboxtv/athtoken_xxxxxx file, here need to be stored the token.

**Comment by LordZork** [comment]
How would I find that from the web interface, since I don't have Homebridge installed on an actual OS?  Would I use Homebridge Terminal?  If so, what commands do I use to get to that directory and view or edit that file?

**Comment by grzegorz914** [comment]
Just use ftp and connect to Homebridge

**Comment by LordZork** [comment]
I can FTP to Homebridge even though it isn't installed on an actual OS?  It is the [Homebridge Raspberry Pi Image](https://github.com/homebridge/homebridge-raspbian-image/wiki/Getting-Started) (it is its own OS).  If this is possible, how would I do that?

**Comment by grzegorz914** [comment]
Just type ftp://addressofhomebridge

**Comment by LordZork** [comment]
It's asking for a password and my homebridge login/password doesn't work.

**Comment by grzegorz914** [comment]
I don't know your login or password

**Comment by LordZork** [comment]
I know.  I am saying my login and password for logging into Homebrige doesn't work when trying to ftp into homebridge.

**Comment by LordZork** [comment]
Do you know the "Homebridge Terminal" commands for changing directories to find the xboxtv directory and files?

**Comment by LordZork** [comment]
I just tested the following...

```
pi@homebridge:/var/lib/homebridge $ /var/lib/homebridge
bash: /var/lib/homebridge: Is a directory

pi@homebridge:/var/lib/homebridge $ /var/lib/homebridge/xboxtv
bash: /var/lib/homebridge/xboxtv: No such file or directory
```

No such file or directory?

**Comment by grzegorz914** [comment]
try xboxTv

**Comment by grzegorz914** [comment]
And check authToken_ipofyourhomebridge file, example authToken_192168110

**Comment by grzegorz914** [comment]
![image](https://user-images.githubusercontent.com/28867813/194664088-cf5ab8e6-7001-4988-a347-b388a84ddec2.png)

**Comment by LordZork** [comment]
> try xboxTv

```
pi@homebridge:/var/lib/homebridge $ ~/.homebridge/xboxTv
bash: /home/pi/.homebridge/xboxTv: Is a directory
pi@homebridge:/var/lib/homebridge $ 
```

That is a directory.  Any idea what commands to use to change to that directory and search that directory?

**Comment by grzegorz914** [comment]
cd

**Comment by grzegorz914** [comment]
list files I directory sleep

**Comment by grzegorz914** [comment]
open file 
vi filename

**Comment by LordZork** [comment]
I'm sorry, I am a noob.  I have been trying variations of CD for a while.  Can you type the entire command here for me, including the CD command and the xboxTv destination?

**Comment by LordZork** [comment]
I am trying to figure this out without having to re-setup Homebridge from scratch, this time by installing it on an actual PS (instead of using the Homebridge image as the OS).  However, I am starting to think I may have no choice.  I am struggling to get to these locations and files.  And I am still wondering if my current setup may be the problem with authentication.

**Comment by LordZork** [comment]
@grzegorz914, I setup a new Homebridge service, which I installed on an actual OS this time (Raspberry Pi OS).

I am experiencing the same issue, only with this setup I am now able to find the associated directories and files.

I found `/var/lib/homebridge/xboxTv/authToken_xxxxxx` and I can see all of the files within...

The authToken is empty and it has the wrong IP in the file name, and I am unable to edit or delete the file.  Also, the folder `/var/lib/homebridge/xboxTv/` is left behind after uninstalling the plugin, and I am unable to delete it.

That said, I decided to try the other Xbox plugin ([Xbox Smartglass](https://github.com/unknownskl/homebridge-smartglass)).  While it has less features, I was able to successfully authenticate it and use all of its features.

Does any of this new info help?  Do you have any suggestions now that I am able to locate the xboxTv directory and files?

I really appreciate any help you can provide!

**Comment by LordZork** [comment]
@grzegorz914, I finally was able to delete the xboxTv folder and start over.  Apparently, Homebridge owns that folder, so I couldn't delete it from within Raspberry Pi OS.  I had to delete it from within Homebridge, via the terminal.

That said, I have tried every possible way of doing this.  I have followed your instructions, and I have tried different versions of your plugin.  It just won't authenticate.

I have looked through the closed issues and have seen others have had the same issue.  It seems very inconsistent when it works and when it doesn't, and sometimes it resolves itself and sometimes it doesn't.  It shouldn't be this hard.  The other Xbox plugin authenticated the first time.

Do you have any ideas?  I'd really like to try your plugin, but I have wasted so many hours and am exhausted.  I need help!

**Comment by LordZork** [comment]
Hi @grzegorz914, would you read my last two posts (before this one) and let me know if you have any advice?

Also, as previously mentioned, the other Xbox plugin ([Xbox Smartglass](https://github.com/unknownskl/homebridge-smartglass)) authenticates easily and successfully on the first try.  I have been using it for almost a month now with no issues—I just wish it had all the same features as your plugin.  That said, I am wondering if you could take a look at how that other plugin authenticates.  Maybe it is a method you could adopt for your plugin?

**Comment by grzegorz914** [comment]
If you can authenticate with other plugin just copy the token from other plugin to this one.

**Comment by LordZork** [comment]
Hi @grzegorz914, thanks for responding!

I just installed your plugin again, but this time I used the token that was authenticated with the other plugin.

After installing the plugin and adding the **Name**, **IP/Hostname**, and **Live ID**, I added the **Web Api Token** (under **Web Api Settings**) and restarted Homebridge.  Then I set the plugin as a child bridge and restarted it again.

That said, I still get the following error in the Homebridge Logs:

`[01/11/2022, 01:34:35] [homebridge-xbox-tv] Device: XXX.XXX.X.XX Xbox, not authorized, please use Authorization Manager.`

While I can turn the Xbox on/off, I am unable to switch inputs (apps, games, etc.) since it is not authorized.

Also, when I open and view the **/var/lib/homebridge/xboxTv/authToken_XXXXXXXXX** file, there is nothing—it is empty.

It seems that the issue is always the same; that the **authToken** file is always empty, no matter what I do or how I authenticate.  Any suggestions?

Any help would be greatly appreciated, thanks!

**Comment by grzegorz914** [comment]
You need copy the auth token from other plug-in authentication file to /var/lib/homebridge/xboxTv/authToken_XXXXXXXXX file

**Comment by LordZork** [comment]
@grzegorz914,

I've been looking through directories and found the directory for the other plugin...

`/usr/local/lib/node_modules/homebridge-smartglass/`

... and I even found this... 

`/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-webapi`

... but I have not been able to find a token file.  Though, it seems like I may have found a reference to one here...

`/usr/local/lib/node_modules/homebridge-smartglass/node_modules/xbox-webapi/src/authentication.js`

Is it possible the plugin is just pulling the token string from the Homebridge Config?

Also, is there a way to just add whatever text is needed—such as that token string—to the token file for your plugin?

I guess I could contact the developer of the other plugin and ask where the token is located.  But I feel like there has to be a way to fix the token file for your plugin without bothering with the other plugin.

**Comment by grzegorz914** [comment]
You need looking for var/lib/Homebridge/.smartglass.tokens.json it is hidden file.

**Comment by LordZork** [comment]
@grzegorz914,

Is it possible to locate and open a hidden file via Homebridge **Terminal**?

Also, what about my previous question?  Is there a way to just add whatever text is needed—such as the token string—to the token file for your plugin, without the need for the other plugin token?

**Comment by grzegorz914** [comment]
just add . before the file name
the token is just text, copy from other file and paste it to your file

**Comment by LordZork** [comment]
@grzegorz914,

I just did this (via Homebridge Terminal)...

`pi@homebridge:/var/lib/homebridge $` `vi .smartglass.tokens.json`

... and it opened a bunch of text.

After all of that text, at the very bottom, it says...

`".smartglass.tokens.json" [Incomplete last line] 1 line, 898964 characters`

I copied all of that text—except for the last line at very the bottom—and pasted it into the authToken file from your plugin.  Also, at the very bottom of your file, it now says...

`"authToken_192168495" 0 lines, 898964 characters`

Assuming this is all okay, how do I save this change via Homebridge Terminal?

**Comment by grzegorz914** [comment]
Saving and Closing the file
Shift+zz – Save the file and quit
:w – Save the file but keep it open
:q – Quit without saving
:wq – Save the file and quit

**Comment by djsomi** [comment]
Hi Guys,

Same issue here, for a while I got Device: not authorized, please use Authorization Manager. 

Just tried to re-authenticate, but plugin creates a 0 byte authToken_ file, so I've did the auth process with the smart glass plugin, and copied the token into this plugin file, and now works fine.

Another hint: If anyone stucked on that xbox device not appearing to add, do a cleanup in Homebridge Setting / "Unpair Bridges / Cameras / TVs / External Accessories" menu.

BR
Zoltan
