### ISSUE TITLE
Updating... No Response

### ISSUE THREAD

**Issue by robinmanuelthiel** [grzegorz914/homebridge-xbox-tv#13]
The device constantly switches between "Updating" and "No Response" mode. I was able to add it successfully, but when opening the Home app, I can never use it. The logs also seem to get spammed a lot with requests.

I have already tried to rename and re-add the accessory and re-start Homebridge.

### Homebridge Logs:
```
...
[4/28/2020, 11:52:33 AM] [XboxTv] Device: 192.168.0.30, name: Xbox One X, state: Online
...
[4/28/2020, 11:54:46 AM] [XboxTv] Device: 192.168.0.30, get current Power state successful, state: ON
[4/28/2020, 11:54:58 AM] [XboxTv] Device: 192.168.0.30, get current Power state successful, state: ON
[4/28/2020, 11:55:10 AM] [XboxTv] Device: 192.168.0.30, get current Power state successful, state: ON
[4/28/2020, 11:56:00 AM] [XboxTv] Device: 192.168.0.30, get current Power state successful, state: ON
[4/28/2020, 11:56:38 AM] [XboxTv] Device: 192.168.0.30, get current Power state successful, state: ON
[4/28/2020, 11:56:49 AM] [XboxTv] Device: 192.168.0.30, get current Power state successful, state: ON
[4/28/2020, 11:57:43 AM] [XboxTv] Device: 192.168.0.30, get current Power state successful, state: ON
```

### Config

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "XXXXX",
        "port": XXXX,
        "pin": "XXXXXXX"
    },
    "accessories": [
      ...
    ],
    "platforms": [
        {
            ...           
        },
        {
            "devices": [
                {
                    "name": "Xbox One X",
                    "host": "192.168.0.30",
                    "xboxliveid": "FDXXXXXXXX",
                    "volumeControl": false,
                    "switchInfoMenu": true
                }
            ],
            "platform": "XboxTv"
        }
    ]
}
```

**Home Bridge version:** 1.0.2
**Plugin Version:** v0.2.3

**Comment by grzegorz914** [comment]
try latest update

**Comment by robinmanuelthiel** [comment]
Isn't jo 0.2.3 the latest one?

**Comment by grzegorz914** [comment]
Please update to the latest version

**Comment by robinmanuelthiel** [comment]
The one you uploaded 2h ago and don't have a changelog for yet? Okay, will try...

**Comment by grzegorz914** [comment]
still the issue open?

**Comment by robinmanuelthiel** [comment]
Kind of, yes. I now get a `device_unavailable` error every 3 seconds in the logs. Is that expected?

![image](https://user-images.githubusercontent.com/5874465/82189715-221b2a00-98f0-11ea-9c11-f5398ac3e125.png)

**Comment by grzegorz914** [comment]
This log is from debug mode, its OK Your Xbox is not available for HB

**Comment by SSutherland94** [comment]
Is there any way to hide this? Or is that not a technical possibility?

**Comment by grzegorz914** [comment]
this is not show, disable debug mode in your Homebridge

**Comment by robinmanuelthiel** [comment]
![image](https://user-images.githubusercontent.com/5874465/82326623-6a644600-99dd-11ea-909c-465bdddad855.png)

I don't think, this only happens in Debug Mode...

**Comment by grzegorz914** [comment]
I think U use old plugin.

**Comment by SSutherland94** [comment]
I have the latest version of the plugin and Homebridge, and I still get this when debug is set to false
`        {
            "name": "Config",
            "port": xx,
            "auth": "form",
            "theme": "red",
            "restart": "pm2 restart homebridge",
            "tempUnits": "f",
            "lang": "auto",
            "sudo": false,
            "debug": false,
            "log": {
                "method": "custom",
                "command": "pm2 logs --raw --out --lines 1000 homebridge"
            },
            "platform": "config"
        },`

**Comment by grzegorz914** [comment]
As 

> I have the latest version of the plugin and Homebridge, and I still get this when debug is set to false
> ` { "name": "Config", "port": xx, "auth": "form", "theme": "red", "restart": "pm2 restart homebridge", "tempUnits": "f", "lang": "auto", "sudo": false, "debug": false, "log": { "method": "custom", "command": "pm2 logs --raw --out --lines 1000 homebridge" }, "platform": "config" },`

get Your log, the log before is from old plugin version

**Comment by SSutherland94** [comment]
![Screen Shot 2020-05-19 at 10 16 20 AM](https://user-images.githubusercontent.com/64995054/82337517-dc2a9880-99b9-11ea-8849-45723eefb635.png)

**Comment by grzegorz914** [comment]
Is Your console available from the local LAN?

**Comment by SSutherland94** [comment]
If you're referring to being able to send shell commands, yes

**Comment by grzegorz914** [comment]
Strange, I do not get this in my log.
This is the part of code and the log is in debug level:

```
this.sgClient.connect(this.host).then(response => {
					this.log('Device: %s %s, state: Online', this.host, this.name);
					this.sgClient.addManager('system_input', SystemInputChannel());
					this.sgClient.addManager('system_media', SystemMediaChannel());
					this.sgClient.addManager('tv_remote', TvRemoteChannel());
					this.getDeviceState();
				}).catch(error => {
					this.log.debug('Device: %s %s, state Offline and error: %s', this.host, this.name, error);
					this.currentPowerState = false;
					return;
				});
```
