### ISSUE TITLE
Unable to add my Xbox to Homekit 

### ISSUE THREAD

**Issue by isaaccs** [grzegorz914/homebridge-xbox-tv#130]
Hi,
 I install your pluging, I can control my XBOX with the HB UI. But I can add it to HK.
Do you have any sugestion ?

**Comment by grzegorz914** [comment]
Please be more specific, what as steps you do? Are you read readme how to ad to HK?

**Comment by isaaccs** [comment]
Yes, I follow the README, but my Xbox is not detected by HK.
I see it and can control it by using the HB UI.
Moreover I have this log every 5 sec 
`[XboxTv] Device: IP XBOX, Socket send 16 bytes.`

**Comment by grzegorz914** [comment]
It not be detected automatically, You need add it manually: https://github.com/grzegorz914/homebridge-xbox-tv#adding-to-homekit

It is first installation of this plugin or was installed before?

**Comment by isaaccs** [comment]
I tried this but nothing happen.

It was install before, I did a clean install also.
````
{
            "devices": [
                {
                    "name": "XBOX",
                    "host": "IP",
                    "xboxLiveId": "ID",
                    "xboxWebApiToken": "TOKEN",
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableDebugMode": true,
                    "webApiControl": true,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "getInputsFromDevice": false,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": false
                }
            ],
            "platform": "XboxTv"
        },
```

**Comment by grzegorz914** [comment]
1. Go to **./homebridge/persist** folder open the file **AccessoryInfo.xxx** one by one and remove this one which contain Your device data, something like this:
`{"displayName":"Xbox","category":34,"pincode":"xxx-xx-xxx","signSk":"821e119153b23b95b435f2a7cf7c55a4d1088b6992c06e7f62be$`
2. Also remove file **IdentifierCashe.xxx** with same name as **AccessoryInfo.xxx**
3. Restart Homebridge and try add it to the Home app again.

**Comment by isaaccs** [comment]
It works!!! 
Thank you
