### ISSUE TITLE
Why are there no GitHub releases after 2.0.0 but still updates?

### ISSUE THREAD

**Issue by vordenken** [grzegorz914/homebridge-xbox-tv#132]
this is kinda confusing, especially because the home bridge UI shows the 2.0.0 Changelog even for the smaller updates...
Maybe you could add releases for smaller updates, just like you did for pre 2.0.0 releases? 

Thanks and keep up the great work!

**Comment by grzegorz914** [comment]
All changes are here: https://github.com/grzegorz914/homebridge-xbox-tv/blob/master/CHANGELOG.md
Only major and minor changes are released to git and show before update in HB.  Patches are displayed also in HB but after update.

**Comment by vordenken** [comment]
I've actually found the Changelog file and also saw the minor patches Changelog after updating.
But is there a reason you handle it this way? For me its very confusing, searching for new hb addons mostly on GitHub and finding yours with a version not matching the version whilst searching/installing it inside home bridge ui.
In my opinion releases are some sort of standard and should show the latest stable version to download (also be the same as the source code in the main branch).
If you don't want to change your style of doing this maybe you could add some sort of disclaimer in the mayor release Changelog?

**Comment by grzegorz914** [comment]
The code on GitHub is alway the same as version published to NPM. Homebridge get plugin updates from NPM not from GitHub. Just Im not release patch versions on GIT, that's all.
