### ISSUE TITLE
Plugin keeps turning the Xbox on by itself

### ISSUE THREAD

**Issue by GodzillaTV** [grzegorz914/homebridge-xbox-tv#144]
My problem is this: I installed the plugin and set it up correctly. Xbox controls work very well too. However, I now have the problem that the Xbox no longer turns off, or rather the plugin sends a switch-on signal to the Xbox every minute. This is pretty bad and so I had to disable the plugin first to get a grip on it temporarily.

**Comment by grzegorz914** [comment]
It’s not true, No any switch-on signal is send every minute only discovery probe. I have 2 consoles in my environment and no one powered ON itself.

**Comment by GodzillaTV** [comment]
Yet. I activated the plugin again and after restarting the homebridge, the Xbox turns on again by itself. Even if I turn off the xbox with the controller or the xbox button, the xbox turns on again. This only happens as long as the plugin is active. So it's obviously the plugin.

**Comment by GodzillaTV** [comment]
OK. I don't know what happened but somehow the Xbox won't start by itself. It could also have been a bug in the Xbox itself, as the Xbox crashed and restarted an hour ago. Now the Xbox with the plugin enabled stays off too. Sorry, but I assumed it was something with the plugin that was turning on the xbox because the homebridge log looked like it. Because every time the Xbox came on, the log said:
[12/20/2022, 9:39:06 PM] [XboxTv] Device: 192.168.1.80 Xbox One X, Connected.
[12/20/2022, 9:39:06 PM] [XboxTv] -------- Xbox One X --------
[12/20/2022, 9:39:06 PM] [XboxTv] Manufacturer: Microsoft
[12/20/2022, 9:39:06 PM] [XboxTv] Model: Xbox One X
and below that, more information about the Xbox
