### ISSUE TITLE
Xbox not turning on

### ISSUE THREAD

**Issue by Stonemeal** [grzegorz914/homebridge-xbox-tv#146]
Hey!
I finally managed to set up everything and I can use homekit to turn off my Xbox or use other features but for some reason the console is not turning on with the plugin. 

This is Xbox Series X, all settings set correctly...

**Comment by grzegorz914** [comment]
Console need to be set ro Instant Power ON if You want to enable it from Home.a.p-
For other functions need to authorize the console  and enable remote control in console settings.

**Comment by grzegorz914** [comment]
Still the issue?
