### ISSUE TITLE
Can’t switch apps error [object, object]

### ISSUE THREAD

**Issue by Smokesalotamus** [grzegorz914/homebridge-xbox-tv#150]
Authorized, WebKit gets input info, can see input changes when done with Xbox, can power on off. Selecting app/game in HomeKit does nothing and gives error [object, object]

**Comment by grzegorz914** [comment]
any log, debug ?

**Comment by Smokesalotamus** [comment]
"Device: 192.x.x.x Xbox Series X, set Input error: [object Object]"

**Comment by grzegorz914** [comment]
Please enable debug mode in plugin config advanced section then get the whole log

**Comment by Smokesalotamus** [comment]
I feel like a dummy.... So, I was messing around with settings on the xbox and realized I didn't have remote play enabled... everything is working now. I appreciate the help tho haha.
