### ISSUE TITLE
Web API Authorization Manager Error

### ISSUE THREAD

**Issue by shanemcw** [grzegorz914/homebridge-xbox-tv#152]
While debugging a Web API error, I cleared my web token and used Authorization Manager processes to create a new one.

When having performed that the first time, the "input" error was cleared but a new error is logged

[1/27/2023, 9:24:53 AM] [homebridge-xbox-tv] Device: 192.168.1.40 XBOX, not authorized, please use Authorization Manager.

I've performed the Authorization Manager process a handful of times, with the same result.

e.g. my latest is 

                {
                    "name": "XBOX",
                    "host": "192.168.1.40",
                    "xboxLiveId": "redacted",
                    "clientId": "5e5ead27-ed60-482d-b3fc-702b28a97404",
                    "xboxWebApiToken": "M.R3_BAY.86b2cf91-947e-e5f7-57be-83dbda9f97e4",
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableDebugMode": false,
                    "webApiControl": true,
                    "volumeControl": 0,
                    "getInputsFromDevice": true,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": false,
                    "sensorPower": false,
                    "sensorInput": false,
                    "sensorScreenSaver": false,
                    "enableMqtt": false,
                    "mqttAuth": false,
                    "mqttDebug": false
                }
            ],
            "_bridge": {
                "username": "0E:E7:D2:24:BA:D4",
                "port": 57008
            },
            "platform": "XboxTv"
        },

copied from from the Authorization Manger URL 
http://localhost:8080/auth/callback?code=M.R3_BAY.86b2cf91-947e-e5f7-57be-83dbda9f97e4

I've restored the original web token using a backup, but the original token gives the error as well

**Comment by grzegorz914** [comment]
Sorry but I can not reproduce this behavior, tested on 2 consoles both clear web token, generate new one all akcept saved restarted and all working correct, no any error. Check your homebridge/xboxTv/ folder for token_xxxx file.

**Comment by shanemcw** [comment]
Thanks for the lead!

Am I looking in the right place?

I do not see a `token_xxxx` file under the

`/var/lib/homebridge/node_modules/homebridge-xbox-tv/ `

tree

nor under the

user "homebridge"'s home

`/home/homebridge`

Thanks for any counsel!

**Comment by shanemcw** [comment]
Thanks for the lead! 

I found an `authtoken_192168140` file in `/var/lib/homebridge/xboxTv`

it is zero bytes

thoughts?

**Comment by grzegorz914** [comment]
So, it’s not stored, are you saved it after create, read carefully what authorizations manager display as tips.

**Comment by shanemcw** [comment]
Thanks for the suggestion!

I proceeded again though all the steps; this time taking screen shots of every step if you need them.

After completion, I checked the `authtoken` file. Its time stamp was updated at the moment I did the authorization followed by a save, but again, zero bytes.

**Comment by shanemcw** [comment]
The I also confirmed the new web token is in the new config. Looks like the auth file was touched during this latest authorization, but nothing written to it.

**Comment by shanemcw** [comment]
Completed the authorization process again after updating to homebridge-xbox-tv v2.4.8.

again the auth file was touched during authorization, but nothing written to it

the file is owned by user `homebridge` with `-rw-r--r--` permissions

**Comment by grzegorz914** [comment]
Can you record video of this process.?

**Comment by shanemcw** [comment]
Prior to the process with current token

<img width="749" alt="Screenshot 2023-01-28 at 1 32 04 PM" src="https://user-images.githubusercontent.com/60005659/215285894-9ca73fa3-7b58-4605-88c8-4457dd3db258.png">

Token cleared

<img width="744" alt="Screenshot 2023-01-28 at 1 32 14 PM" src="https://user-images.githubusercontent.com/60005659/215285895-ffec1788-cfba-4ea5-88ba-97f94bc2dbdc.png">

Start authorization pushed

<img width="743" alt="Screenshot 2023-01-28 at 1 32 25 PM" src="https://user-images.githubusercontent.com/60005659/215285896-d0119b78-6919-4646-a84b-9cbd8a234655.png">

URL launched

<img width="644" alt="Screenshot 2023-01-28 at 1 32 38 PM" src="https://user-images.githubusercontent.com/60005659/215285897-aa99084d-5079-4260-91e4-3a5b06226e15.png">

Cut and pasted into field

<img width="740" alt="Screenshot 2023-01-28 at 1 32 53 PM" src="https://user-images.githubusercontent.com/60005659/215285898-a0fa5b26-bc3a-4bad-a5f1-5bb31c1905c5.png">

Save button pushed

<img width="738" alt="Screenshot 2023-01-28 at 1 33 02 PM" src="https://user-images.githubusercontent.com/60005659/215285899-4b989262-b437-4e02-868a-f75a5619a954.png">

New token showing under plugin settings

<img width="721" alt="Screenshot 2023-01-28 at 1 33 37 PM" src="https://user-images.githubusercontent.com/60005659/215285900-0fced8cd-bfe4-42b7-afcc-435da6ebd96d.png">

Directory showing the auth file was touched during this process but zero bytes

<img width="548" alt="Screenshot 2023-01-28 at 1 44 07 PM" src="https://user-images.githubusercontent.com/60005659/215285901-cbee8726-c602-4118-9fc3-b3e632f23d19.png">

**Comment by grzegorz914** [comment]
You don’t press activate console on last screenshot

**Comment by shanemcw** [comment]
derp … Thanks. I didn't notice that button changed labels and needed to go back to the first button to do the last step LOL. I appreciate your time. Looks like the original issue's cause may have needed a re-issue of a new token. Will continue testing.

**Comment by shanemcw** [comment]
Can't find your "donate" button LOL

**Comment by grzegorz914** [comment]
I don’t have donate button, so I close this issue as solved.

**Comment by shanemcw** [comment]
follow-up question:

<img width="694" alt="Screenshot 2023-01-28 at 2 15 44 PM" src="https://user-images.githubusercontent.com/60005659/215286783-1cd4c15d-2342-49d4-9dd5-c884b10ed315.png">

am I looking in the correct place for "display tips on top of authorizations manager"

**Comment by grzegorz914** [comment]
Yes, marked place changed during press buttons
![B0F608A9-23C2-4727-997D-1282E0646423](https://user-images.githubusercontent.com/28867813/215286989-82309b75-2f34-48b6-b7ba-546f48c8bacd.jpeg)

**Comment by shanemcw** [comment]
Much appreciated—you are very gracious. Have great weekend!
