### ISSUE TITLE
Xbox won’t appear in the Home app

### ISSUE THREAD

**Issue by TomLake** [grzegorz914/homebridge-xbox-tv#155]
Hi,

I had this plugin working for a long time, but something broke. I removed my Xbox as an accessory in the Home app and now it won’t appear under More options… unless I change the ‘xbox network live id’ to something different to the original ‘live id’ in the config. However, that obviously makes the plugin not work correctly.

It works fine in Homebridge UI.

I have tried restarting all home hubs, iPhone, Homebridge, reinstalling the xbox-tv plugin. Nothing makes my Xbox appear to add again.

I have tried setting the ‘live id’ to a random string in the config, then adding the Xbox to the home app, then changing the config back to my actual ‘live id’. That lets the home app see the Xbox but it has no response as soon as I change the ‘live id’ to the correct one.

It seems that the Home app won’t let me re-add a recently removed Xbox with the same serial number. I hope this makes sense to you.

I’m wondering if it would be possible to have another field for a false serial number that HomeKit can use, instead of using the ‘Xbox network live id’ as the serial number for HomeKit.

Regards,
Tom

**Comment by grzegorz914** [comment]
arę You read this: https://github.com/grzegorz914/homebridge-xbox-tv/wiki#troubleshooting

**Comment by TomLake** [comment]
Hi,

Thank you! I used the a tool in the Homebridge UI settings. It worked!

[image0.jpeg]

Thanks for a quick reply and great plugin.



On 13 Feb 2023, at 15:27, Grzegorz ***@***.***> wrote:

﻿

arę You read this: https://github.com/grzegorz914/homebridge-xbox-tv/wiki#troubleshooting
