### ISSUE TITLE
Authorization buttons do nothing

### ISSUE THREAD

**Issue by WelshMcSpicy** [grzegorz914/homebridge-xbox-tv#157]
Hi,
Using Homebridge/UI v 1.6.0 and the latest XBOX TV plugin. Installed it as a child.
Edited the JSON to include XBOX Series X IP Address. 
In the Authorization screen, Name & Host IP are displayed. Web Api Token is blank. Clicking any of the buttons (except save/close) does nothing.

**Comment by shanemcw** [comment]
Getting the same behavior. Downgraded to a previous version authorize then upgraded again.
Seeing other issues with latest builds while installing from scratch (plugin, unpaired, etc.) (will create a new ticket)

**Comment by WelshMcSpicy** [comment]
Got it working. Reinstalled and entered the IP and XBOX Device ID from the initial setup instead of editing the JSON.
Now the XBOX is recognized. Just have to figure out the buttons necessary to open/run specific games.

**Comment by WelshMcSpicy** [comment]
Update: The logs show positive things like, "Device <IP> XBOX Connected". However, the Authorization GUI is still not showing a Web Api Token and none of the authorization buttons are responding.

**Comment by grzegorz914** [comment]
Connected it’s not the same as Authorized. You need paste Web Api Token itself after generate it. Use Authorization manager to Authorize Your Console. To get it worth need to ad IP Adresse and xboxLiveId.

**Comment by shanemcw** [comment]
Same issue with me; authorization buttons are unresponsive on a fresh plugin install after input of IP address and LiveID —after about version 2.5. Downgrading to version 2.50 then the Authorization Manager works as documented.

**Comment by WelshMcSpicy** [comment]
> Connected it’s not the same as Authorized. You need paste Web Api Token itself after generate it. Use Authorization manager to Authorize Your Console. To get it worked need to ad IP Adresse and xboxLiveId in plugin settings first.

I have already added IP address and xboxliveid in the settings. However, the Authorize buttons do nothing. Only SAVE and CLOSE work.

**Comment by WelshMcSpicy** [comment]
Update. 
Thanks @shanemcw - I downgraded to v 2.5, and the authorization buttons are now working. 

However, after AUTHORIZE CONSOLE, my browser gets redirected to "http://localhost:8080/auth/callback?code=M.R3_BAY.1e17534e-7fd5-d13f-0caa-33a66342a481" and gives me "This site can’t be reachedlocalhost refused to connect". Tried it on both Safari and Chrome. Same result.

**Comment by grzegorz914** [comment]
You need copy this `M.R3_BAY.1e17534e-7fd5-d13f-0caa-33a66342a481` and paste as Web Apoi Token.

**Comment by WelshMcSpicy** [comment]
> You need copy this `M.R3_BAY.1e17534e-7fd5-d13f-0caa-33a66342a481` and paste as Web Apoi Token.

Thanks. Did this and restarted (still on v 2.5). Get the following error in the logs and the child repeatedly terminates and restarts. Note that I then upgraded to the latest version...this error no longer happens, but instead, I get. Is the token I generated from authorization with v 2.5 still ok when I upgrade to 2.8.1?

[2/20/2023, 1:49:53 PM] [homebridge-xbox-tv] Device: 192.168.1.47 XBOX SERIES X, check authorization state error: No oauth token found. Use authorization manager first., recheck in 60se.

===== v 2.5 error =====
/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-webapi/src/authentication.js:378
            this._tokens = JSON.parse(token_store)
                                ^
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.loadTokens (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-webapi/src/authentication.js:378:33)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-webapi/src/authentication.js:355:26)
    at new Promise (<anonymous>)
    at Object.isAuthenticated (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-webapi/src/authentication.js:353:20)
    at Object.isAuthenticated (/usr/local/lib/node_modules/homebridge-xbox-tv/node_modules/xbox-webapi/src/client.js:54:41)
    at XBOXDEVICE.getAuthorizationState (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:328:41)
    at new XBOXDEVICE (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:192:9)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-xbox-tv/index.js:43:5)
    at HomebridgeAPI.emit (node:events:513:28)

**Comment by grzegorz914** [comment]
You need use authorization manager, and the process need to be successfully done. Paste Web Api Toke into the Config is nothing. Install 2.I.1 and go through the process, are only 3 steps.

**Comment by WelshMcSpicy** [comment]
> You need use authorization manager, and the process need to be successfully done. Paste Web Api Toke into the Config is nothing. Install 2.I.1 and go through the process, are only 3 steps.

Install which version?

**Comment by grzegorz914** [comment]
Mąkę video how do you authorize the console please

**Comment by WelshMcSpicy** [comment]
Here's a DropBox link to the recording: https://www.dropbox.com/s/l8s9nlyen0c0xm9/Homebridge.mp4?dl=0

**Comment by grzegorz914** [comment]
You have missing 1 step, press activate console button after paste token. You can update to 2.8.2 where authorization manager is more simply. Only 1 button to authorize console. 
1. Press clear token button
2. Press Start authorization button
3. Paste token
4. Press activate console button
5. Done

**Comment by WelshMcSpicy** [comment]
Thanks. That worked. Appreciate the patience.
