### ISSUE TITLE
Forking and implementing a bash command at "On"

### ISSUE THREAD

**Issue by 10w73** [grzegorz914/homebridge-xbox-tv#159]
As a rookie python dev I'm not that good with java script related stuff. I want to fork it and implement a bash command when the Xbox is supposed to start (since I got it in shutdown mode for energy saving puposes). 

`irsend -# 3 SEND_ONCE xboxOne KEY_ON`

Would somebody pls explain me how to do that? And in a way that I easily can merge future updates, I never done that before here.

Thx in advance! :)

**Comment by grzegorz914** [comment]
This command need separate infra rot transmitter to send command.

in node can be used:
```
const { exec } = require('child_process');

const command = 'irsend -# 3 SEND_ONCE xboxOne KEY_ON';
exec(command, (error, stdout, stderr) => {
  if (error) {
    console.error(`exec error: ${error}`);
    return;
  }
  console.log(`stdout: ${stdout}`);
  console.error(`stderr: ${stderr}`);
});
```

**Comment by 10w73** [comment]
Its working! I had to use a pipe and different commands to achieve it because my homebridge runs in a docker container but it is working. Great stuff.
