### ISSUE TITLE
Apps change and remote working partially

### ISSUE THREAD

**Issue by AdrianAguilarT** [grzegorz914/homebridge-xbox-tv#16]
If i open an app with Xbox controller, it changes to the app on Home app and show a message  in logs, but if i open an app from Home app show a message on log for opening, but Xbox does nothing. 

Remote on CC only changes the volume and play/pause. Other buttons doesn’t working.

**Comment by AdrianAguilarT** [comment]
I have noticed that the same problems occurs with Xbox App from AppStore. 

I restarted my Xbox and remote Widget is now fully working. 🙌🏻

But changing apps not working on Xbox App and Home App. Some suggestion?

**Comment by grzegorz914** [comment]
Changing apps is not possible, the api does not contain this feature right now.

**Comment by AdrianAguilarT** [comment]
Ok. That’s bad, cause Xbox app still having the option to start games.

But is not your issue, so i close it.
