### ISSUE TITLE
since update i cant activate consol

### ISSUE THREAD

**Issue by MattRoe84** [grzegorz914/homebridge-xbox-tv#162]
Hi since the latest update when i click the start activation button no page pops up as per the message meaning im unable to link my consol

**Comment by grzegorz914** [comment]
May be popup blocked, what is displayed in the Authorization Manager?

**Comment by grzegorz914** [comment]
same for me wait....

**Comment by grzegorz914** [comment]
No any bug, was popup window blocked in my safari web browser, for some unknown reason after yesterday system update.
Nów is open as excepted.

**Comment by grzegorz914** [comment]
<img width="815" alt="Zrzut ekranu 2023-03-1 o 16 36 18" src="https://user-images.githubusercontent.com/28867813/222187490-dbd03f09-24b8-4618-b552-573850461cfb.png">

**Comment by MattRoe84** [comment]
thanks it was the pop up blocker issue, all fixed now, thanks for your help
