### ISSUE TITLE
Bridge Connected but not the Device itself

### ISSUE THREAD

**Issue by Severin99** [grzegorz914/homebridge-xbox-tv#167]
Hi, thanks for the plugin. I have cnnected the bridge to my homekit but cannot see the xbox in my application. Can you help me?

Homebridge running on Synology NAS
Xbox Series X
Already Hue Plugin running
No XBOX Live connected (just want to turn on and off)

**Comment by grzegorz914** [comment]
Look in wiki

**Comment by Severin99** [comment]
New in GitHub. Where can I find it?

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv/wiki

**Comment by Severin99** [comment]
Thanks. I removed the Files but its still not working after rebooting homebridge. Have you got another idea?

**Comment by Severin99** [comment]
![image](https://user-images.githubusercontent.com/128243303/226120565-4ea83ca5-a988-4dc8-a3ce-75a1c6fd14d8.jpeg)

**Comment by Severin99** [comment]
Is it enough to insert the IP for just turning ON/OFF ?
Because in Homebridge / Devices there is an XBox and Xbox-Speaker but the xbox doesn`t react to both of them.

**Comment by grzegorz914** [comment]
You need add the accessory to the home.app, itd not display automatically.

**Comment by grzegorz914** [comment]
IP and Xbox LiveID

**Comment by grzegorz914** [comment]
Please read readme carefully

**Comment by Severin99** [comment]
Sorry realy not want to do waste your time But its still Not working. Is the Xbox Live ID the console ID?

**Comment by grzegorz914** [comment]
Here is all descriebed:
https://github.com/grzegorz914/homebridge-xbox-tv#configuration
