### ISSUE TITLE
logs

### ISSUE THREAD

**Issue by apexad** [grzegorz914/homebridge-xbox-tv#17]
```bash
[5/2/2020, 03:41:59] [XboxTv] Device: 192.168.0.40, name: Xbox One X, state: Offline, error: {
  error: 'device_unavailable',
  message: 'Xbox is unavalable on 192.168.0.40'
}
```
Can you add a config option to disable this log?

**Comment by JimmyEyeball** [comment]
Yes this would be handy to stop getting so many alerts on Telegram without having to disable alerts for the whole instance....

**Comment by JimmyEyeball** [comment]
No Joy???

**Comment by grzegorz914** [comment]
Moved to debug.

**Comment by SSutherland94** [comment]
I have debug logging disabled on my Homebridge, but still receive these messages every three seconds, and I have two Xbox consoles so my log fills up rather quickly
