### ISSUE TITLE
Reporting Xbox state as “Xbox Guide” when playing game

### ISSUE THREAD

**Issue by HawaiiBoi32** [grzegorz914/homebridge-xbox-tv#176]
[5/27/2023, 12:34:46 PM] [homebridge-xbox-tv] Device: 192.168.1.4 Xbox Series X,
Inp
ut: Xbox Guide, Reference: Xbox. Guide_8wek yb3d8bbwe!Xbox.Guide.Application, Product Id: XboxGuide

Plug-in keeps reporting state as Xbox guide. Not sure why this is.
I have web api authorized, and only have games loaded for input. None of the other apps.

**Comment by grzegorz914** [comment]
https://support.xbox.com/en-US/help/hardware-network/getting-started-set-up/using-the-guide
