### ISSUE TITLE
How often to re-authorize the console?

### ISSUE THREAD

**Issue by angeloghisi** [grzegorz914/homebridge-xbox-tv#177]
Hi, the plug-in works quite well.

However I have a question: how often do I need to re-authorize the console?
I mean: sometimes it works for weeks and I can turn my Xbox on from Home app without any problem. Sometimes after a couple of days I try to turn my Xbox on and it’s not working.
When I open HomeBridge interface I find out that the plug-in needs to be re-authorized.

How often does the plug-in need a new API token? Is there a way to be able to get a notification when the plug-in needs a new authorization? This would be useful to avoid plug-in malfunctions (that in fact are not plug-in malfunctions but need for authorization).

thank you very much

**Comment by grzegorz914** [comment]
To reautgorize console Just Clear Web API Token and start authorization again.

**Comment by Captainkyle420** [comment]
angeloghisi, I am having the same issue. It used to give an option to stay signed in. But doesn’t anymore. I am trying a to work around it. Seeing if I log out of Microsoft & clear sign in cookies on my browser (on the device I am using the home bridge gui on) then sign in before I use the Xbox tv authorize manager. And select stay signed in then login with the Xbox authorization manager. And will see if the stay signed in carries over. Will keep you posted

**Comment by angeloghisi** [comment]
@grzegorz914 yes I know how authorization works, I do it every time the authorization expires.
My question was: is there a way to avoid authorization expiration or at least being notified if it’s expired?
Sometimes I get home, I want to turn my Xbox on and it does not work… I have to open HomeBridge interface and go through the entire process of re-authorization.
Nothing serious, but I thought it would be nice asking.

Thanks for your work

**Comment by angeloghisi** [comment]
@Captainkyle420 ok thank you very much, let me know if you find out something new

**Comment by torandreroland** [comment]
I'm having the same problem with the need for reauthorization. This is especially unfortunate since this plugin eventually consumes all resources on the machine (see issue #172).

I'm thinking there is room for improvement here with how this plugin handles tokens. Without looking into how the plugin handles authentication and authorization, but assuming it's based on OIDC and OAuth 2.0, the plugin should use an [authorization flow](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/#What-Is-a-Refresh-Token) that lets it refresh an access token based on a refresh token, thus bypassing the need to authenticate again.

**Comment by grzegorz914** [comment]
Will be fixed ASAP.

**Comment by grzegorz914** [comment]
Please check latest beta and let me know.

**Comment by muzzymate** [comment]
Thank you. Just installed latest beta and will report back. Was having same issue where I was constantly loosing authorization.

**Comment by grzegorz914** [comment]
@shanemcw 
this error have nothing to do with, if you see this error always open new issue pleas.

**Comment by angeloghisi** [comment]
The last beta is working for some days now, no need to re-authorize at the moment.

I’ll keep you updated in the next days.

thank you
