### ISSUE TITLE
Hoobs Setup

### ISSUE THREAD

**Issue by notorioustubze** [grzegorz914/homebridge-xbox-tv#18]
Hi, I've just recently come across this plug in and I'm trying to use it with Hoobs. The log say's it found the xbox and connected successfully however I can't seem to get the xbox to show in home kit. Any help greatly appreciated. Thanks in advance!
So far I've stopped/started the service.
closed home app and re-opened.
rebooted Hoobs server.
<img width="1570" alt="Screenshot 2020-05-03 at 21 26 16" src="https://user-images.githubusercontent.com/53260708/80925212-de6be080-8d85-11ea-99ba-5451d7d2b06b.png">
<img width="1267" alt="Screenshot 2020-05-03 at 21 27 19" src="https://user-images.githubusercontent.com/53260708/80925214-df9d0d80-8d85-11ea-8e36-7a79589ca3b0.png">

**Comment by grzegorz914** [comment]
Have U added this in HomeKit app pressed + on Top right and select add accessory?

**Comment by notorioustubze** [comment]
> Have U added this in HomeKit app pressed + on Top right and select add accessory?

I hadn't... Apologies for wasting your time! Loving the plugin already :)
