### ISSUE TITLE
WHERE IS the AUTHORIZATION MANAGER?

### ISSUE THREAD

**Issue by Myth0zz** [grzegorz914/homebridge-xbox-tv#181]
Hello, I use HOOBS 4.0 and your plugin. I have installed it, found the IP, the LiveID etc. I cannot find the authorization link:

- First of all please use built in Authorization Manager.
- Start new authorization need remove old token first, to clear token use Authorization Manager GUI.
- Make sure Your web browser do not block pop-up window, if Yes allow pop-up window for this app.

WHERE IS the AUTHORIZATION MANAGER? :)

**Comment by grzegorz914** [comment]
You need to have installed Config UI X and ther in plugin settings.

**Comment by Myth0zz** [comment]
Thank for replying!

Since I am not experienced with CLI could you please give me a hint on how to install it in my HOOBS? I have a Mac connected to it as well with terminal connection, if these help. :)

Another similar plugin (Smartglass) gives a url in logs when run - click it and authorization is done. This is also much easier for us not experienced users :)


Sent from my iPhone

On 21 Sep 2023, at 19:32, Grzegorz ***@***.***> wrote:

﻿

You need to have installed Config UI X and ther in plugin settings.

**Comment by Myth0zz** [comment]
Thanks but I have seen all these things.

I won’t go through this whole procedure just to get an authorization token.

I’d wish it was easier. Thanks anyway for replying. I will uninstall the plugin. I can live without Xbox in my HomeKit. 😅

Keep up the good work.


Sent from my iPhone

On 21 Sep 2023, at 19:38, Grzegorz ***@***.***> wrote:

﻿

https://github.com/homebridge/homebridge-config-ui-x/wiki

**Comment by grzegorz914** [comment]
The procedure is just 3 steps.
