### ISSUE TITLE
404 on WakeUp with Beta 209

### ISSUE THREAD

**Issue by shanemcw** [grzegorz914/homebridge-xbox-tv#182]
Receiving this 404 on the attempt to power on with Beta 209

`[10/3/2023, 3:10:26 PM] [XboxTv] Device: 192.168.0.23 Xbox, set Power, error: send command type: Power, command: WakeUp, params: , error: AxiosError: Request failed with status code 404`

**Comment by shanemcw** [comment]
RESOLVED
A console reset restored the console to functioning with the plugin.

**Comment by trevnologies** [comment]
> RESOLVED A console reset restored the console to functioning with the plugin.

Are you saying you factory reset the xbox or are you saying you unplugged or rebooted the xbox? I am also having this issue now which is why I as for clarification. Thank you.

**Comment by shanemcw** [comment]
Thanks @trevnologies for the question—not a factory reset, but a power cycle reboot.
