### ISSUE TITLE
Azure api question

### ISSUE THREAD

**Issue by DjDave96** [grzegorz914/homebridge-xbox-tv#185]
ok so the question i have is that the url code i use to connect to my homebridge is http://homebridge.local:9686/ and is being run on a raspberry pi and my problem is when i go to microsoft azure to create the app i Use the url http://homebridge.local:9686/auth/callback and i get a error in azure. Is it posible to run it from raspberry pi and what is the fix for my problem.

**Comment by grzegorz914** [comment]
Not a plugin problem, this question please post on RPI forum
