### ISSUE TITLE
The HomeKit Tv remote is not working

### ISSUE THREAD

**Issue by dossiedockett** [grzegorz914/homebridge-xbox-tv#19]
Instead of a list, I get separate controls for my games.

**Comment by dossiedockett** [comment]
{
            "platform": "XboxTv",
            "devices": [
                {
                    "name": "Xbox One S",
                    "host": "XXXXXXXX",
                    "xboxliveid": "XXXXXXXXXXXX",
                    "volumeControl": true,
                    "switchInfoMenu": true,
                    "apps": [
                        {
                            "name": "Fortnite",
                            "reference": "Fortnite_d5xxtpggmzx6p!AppFortnite"
                        },
                        {
                            "name": "Minecraft",
                            "reference": "Microsoft.MinecraftUWPConsole_8wekyb3d8bbwe!App"
                        }
                    ]
                }
            ]
        }

**Comment by grzegorz914** [comment]
What iOS U use?

**Comment by apexad** [comment]
It is now `inputs` not `apps`.

**Comment by grzegorz914** [comment]
Yes, it was described in changelog and README.
