### ISSUE TITLE
Cannot turn off Xbox & On/Off state not reflected correctly

### ISSUE THREAD

**Issue by zvuc** [grzegorz914/homebridge-xbox-tv#190]
Hi, I just set up the plugin today. While turning on the Xbox through the home accessory in the Home App seems to work fine, I can't turn off the console from the app in any way. It also seems the on/off state is not reflected correctly.

Pressing the power button on the home app accessory does seem to send power on signal, because on my Xbox screen it shows a notification saying 'Xbox is already on'.

Is there something I may be missing here?

**Comment by grzegorz914** [comment]
can you post debug log, go to Advanced Settings>>System>>>Debug enable it restart plugin and get the whole log
