### ISSUE TITLE
Device: 192.168.1.31 Xbox, Send connect request error: Read token error: TypeError: Cannot read properties of undefined (reading 'Token')

### ISSUE THREAD

**Issue by aberthil** [grzegorz914/homebridge-xbox-tv#192]
Since the past few days a new error message is popping up even though I did not change my configuration at all.
Any help would be great so that we can remove this error message.
I am running the plugin as a child in homebridge

Here is my configuration
{
    "bridge": {
        "name": "Homebridge 32DD",
        "username": "0E:44:64:DB:32:DD",
        "port": 51803,
        "pin": "214-42-102",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "devices": [
                {
                    "name": "Xbox",
                    "host": "192.168.1.31",
                    "xboxLiveId": "FD00C4B70C15475F",
                    "webApiControl": false,
                    "getInputsFromDevice": false,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": false,
                    "inputsDisplayOrder": 0,
                    "buttons": [
                        {
                            "namePrefix": false
                        }
                    ],
                    "sensorPower": false,
                    "sensorInput": false,
                    "sensorScreenSaver": false,
                    "sensorInputs": [
                        {
                            "namePrefix": false
                        }
                    ],
                    "webApiPowerOnOff": false,
                    "webApiRcControl": false,
                    "webApiVolumeControl": false,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableRestFul": false,
                    "restFulDebug": false,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttAuth": false,
                    "webApiToken": "M.C107_BAY.2.a3241162-abc9-89f5-559a-8984e509030d",
                    "inputs": [
                        {
                            "name": "Blu-ray Player",
                            "reference": "Microsoft.BlurayPlayer_8wekyb3d8bbwe!Xbox.BlurayPlayer.Application",
                            "oneStoreProductId": "9NBLGGH4VVD4",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Fortnite",
                            "reference": "436609B6.FortniteClient_9ncxwbgmmv7m8!AppFortnite",
                            "oneStoreProductId": "BT5P2X999VH2",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "ARK: Survival Evolved",
                            "reference": "ARKSurvivalEvolved_2wc4svk0vzm80!ShooterGame",
                            "oneStoreProductId": "BNBLC4ZGFNKB",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Cuphead",
                            "reference": "Cuphead_32yh0mcy5nszr!App",
                            "oneStoreProductId": "9NJRX71M5X9P",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "F1 2018",
                            "reference": "F12018_62ktj6msykznt!F12018Master",
                            "oneStoreProductId": "C2N5TTQ86BC6",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "FIFA 19",
                            "reference": "FIFAGame19-NA_zwks512sysnyr!FIFAGame.App",
                            "oneStoreProductId": "C3C71TV51SQC",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Slime Rancher",
                            "reference": "MonomiPark.SlimeRancher_63zvbkpt4c9hy!App",
                            "oneStoreProductId": "C2NC88M7NWZ1",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Apex Legends",
                            "reference": "Apex_zwks512sysnyr!r5.App",
                            "oneStoreProductId": "BV9ML45J2Q5V",
                            "type": "APPLICATION"
                        }
                    ]
                }
            ],
            "platform": "XboxTv"
        }
    ]
}

**Comment by aberthil** [comment]
The plugin version is v2.10.3

**Comment by aberthil** [comment]
Sorry but need to ask you a bit of clarifccation here
You want me to change these two files with these two new lines, correct?
What is the whole path of these files exactly so that I can find them?
Thank you.
Alexis

**Comment by grzegorz914** [comment]
Just update the plugin to the latest version.

**Comment by aberthil** [comment]
Much easier indeed.
Thank you for the prompt support
Always appreciated
