### ISSUE TITLE
Error while trying to authenticate via Homebridge UI

### ISSUE THREAD

**Issue by hasrt1206** [grzegorz914/homebridge-xbox-tv#196]
I get the following error while authenticating through homebridge.
Any help will be appreciated.

Authorization error: { "message": "Request failed with status code 400", "name": "AxiosError", "stack": "AxiosError: Request failed with status code 400\n at settle (/var/lib/homebridge/node_modules/homebridge-xbox-tv/node_modules/axios/dist/node/axios.cjs:1967:12)\n at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-xbox-tv/node_modules/axios/dist/node/axios.cjs:3066:11)\n at IncomingMessage.emit (node:events:529:35)\n at endReadableNT (node:internal/streams/readable:1400:12)\n at process.processTicksAndRejections (node:internal/process/task_queues:82:21)\n at Axios.request (/var/lib/homebridge/node_modules/homebridge-xbox-tv/node_modules/axios/dist/node/axios.cjs:3877:41)\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n at async /var/lib/homebridge/node_modules/homebridge-xbox-tv/src/webApi/authentication.js:177:34", "config": { "transitional": { "silentJSONParsing": true, "forcedJSONParsing": true, "clarifyTimeoutError": false }, "adapter": [ "xhr", "http" ], "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1, "maxBodyLength": -1, "env": {}, "headers": { "Accept": "application/json, text/plain, */*", "Content-Type": "application/x-www-form-urlencoded", "User-Agent": "axios/1.6.7", "Content-Length": "291", "Accept-Encoding": "gzip, compress, deflate, br" }, "Content-Type": "application/x-www-form-urlencoded", "method": "post", "url": "https://login.live.com/oauth20_token.srf", "data": "client_id=xxxxxxxxxxxxx5c2cf12a3290&grant_type=authorization_code&scope=XboxLive.signin%20XboxLive.offline_access&code=xxxxxxxxxxxxxxxx770a20a70a8b&redirect_uri=http%3A%2F%2Flocalhost%3A8888%2Fauth%2Fcallback&client_secret=xxxxxxxxxxxxxxxx" }, "code": "ERR_BAD_REQUEST", "status": 400 }

**Comment by SAWKIT-17** [comment]
Same

**Comment by grzegorz914** [comment]
try 3.0.2 and let me know

**Comment by awallace916** [comment]
3.0.2 Fixed it for me! Thank you so much!
