### ISSUE TITLE
XboxTV not displaying in home app but its in homebridge ui

### ISSUE THREAD

**Issue by rappc87** [grzegorz914/homebridge-xbox-tv#198]
When adding accessories to Homekit, only the bridge is visible. It does not appear as a separate device and I cannot add it. When adding accessories to Homekit, only the bridge is visible. It does not appear as a separate device and I cannot add it. but it works and appears properly in homebridge > accessories.

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv/wiki#troubleshooting
