### ISSUE TITLE
(node:1978) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'connectionStatus' of undefined

### ISSUE THREAD

**Issue by skitzow88** [grzegorz914/homebridge-xbox-tv#2]
0|homebridge -I  | [3/3/2020, 5:04:23 PM] [XboxTv] Device: 192.168.0.203, name: Game console, state: Connected
0|homebridge -I  | (node:1978) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'connectionStatus' of undefined
0|homebridge -I  |     at /usr/lib/node_modules/homebridge-xbox-tv/index.js:102:26
0|homebridge -I  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|homebridge -I  | (node:1978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
0|homebridge -I  | (node:1978) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

![Screenshot 2020-03-03 at 17 06 05](https://user-images.githubusercontent.com/56042035/75794662-68d99900-5d71-11ea-8940-a3fe6d7645a2.png)

**Comment by grzegorz914** [comment]
Update and check again

**Comment by skitzow88** [comment]
Will do right away!

**Comment by skitzow88** [comment]
XboxTv] Device: 192.168.0.203, name: Xbox One, state: Connected
0|homebridge -I  | (node:27595) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sgClient' of undefined
0|homebridge -I  |     at /usr/lib/node_modules/homebridge-xbox-tv/index.js:104:9
0|homebridge -I  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|homebridge -I  | (node:27595) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
0|homebridge -I  | (node:27595) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by grzegorz914** [comment]
Please update again

**Comment by skitzow88** [comment]
No error after update from minutes ago. But device will give no response.

**Comment by grzegorz914** [comment]
Check again

**Comment by skitzow88** [comment]
Did try again, no error message does say it is connected but device enters unresponsive state when switching on/off. Did had the smartglass plugin installed previously, does this have anything to do with it?

**Comment by grzegorz914** [comment]
I can not test this property because I’m not at home but I prepared some update.
Please check and report again.

**Comment by skitzow88** [comment]
0|homebridge -I -D  | [3/11/2020, 6:54:50 PM] TypeError: Cannot read property 'sgClient' of undefined
0|homebridge -I -D  |     at /usr/lib/node_modules/homebridge-xbox-tv/index.js:320:12
0|homebridge -I -D  |     at xboxTvDevice.getPowerState (/usr/lib/node_modules/homebridge-xbox-tv/index.js:308:3)
0|homebridge -I -D  |     at xboxTvDevice.setPowerState (/usr/lib/node_modules/homebridge-xbox-tv/index.js:313:6)
0|homebridge -I -D  |     at Characteristic.Active.emit (events.js:311:20)
0|homebridge -I -D  |     at Characteristic.Active.Characteristic.setValue (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
0|homebridge -I -D  |     at Accessory.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:882:22)
0|homebridge -I -D  |     at Array.forEach (<anonymous>:null:null)
0|homebridge -I -D  |     at Accessory._handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:822:8)
0|homebridge -I -D  |     at HAPServer.emit (events.js:311:20)
0|homebridge -I -D  |     at HAPServer._handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:974:10)
0|homebridge -I -D  |     at HAPServer.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
0|homebridge -I -D  |     at IncomingMessage.emit (events.js:311:20)
0|homebridge -I -D  |     at endReadableNT (_stream_readable.js:1204:12)
0|homebridge -I -D  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
