### ISSUE TITLE
Authorisation page

### ISSUE THREAD

**Issue by Ollie9270** [grzegorz914/homebridge-xbox-tv#202]
When i click start authorisation no page opens. I have made sure pop up are allowed and everything. Just nothing happens. 
![IMG_3109](https://github.com/grzegorz914/homebridge-xbox-tv/assets/174746501/7a8fc24b-a0da-47a0-9e6b-d840e39a44d8)
Just that text shows up. Ive then input a web api for a different app just to see if that would work and it did not. Said “bad request” how to i get it to approve. I have managed to before about a year ago but recently had to reset my home bridge.

**Comment by awallace916** [comment]
I'm having this same issue.

**Comment by grzegorz914** [comment]
fixed in 3.0.2
