### ISSUE TITLE
Xbox TV might not be ready for Homebridge v2.0

### ISSUE THREAD

**Issue by JasonGoldenDDT** [grzegorz914/homebridge-xbox-tv#205]
Receiving this message from homebridge this morning. 

**What support can this community provide to support this remediation?**

<img width="793" alt="Screenshot 2024-08-29 at 7 36 52 AM" src="https://github.com/user-attachments/assets/9b9cd78c-47bf-4e84-8841-45f3b53ba62a">

**Comment by grzegorz914** [comment]
It’s ready
