### ISSUE TITLE
Expanding the list...

### ISSUE THREAD

**Issue by JimmyEyeball** [grzegorz914/homebridge-xbox-tv#21]
Any way of expanding the apps list....  Now that we can see the app IDs in the logs I see it is possible to replace the apps in the stock list and it seems to see them fine,,, But is there any way to expand the list to add more as required???

Its seems to be limited to the first 6 and seems to see any of the first 6 if I replace them with anything ie. swap AirServer for Plex and Homekit sees it fine but if you add any more than 6 it doesn't seem to see any Homekit just shows as blank...

"platforms": [{
		"platform": "XboxTv",
		"devices": [{
			"name": "LIVINGROOM-XBOX",
			"host": "192.168.1.27",
			"xboxliveid": "FD0068E7xxxxxxxx",
			"volumeControl": false,
			"switchInfoMenu": true,
			"inputs": [{
					"name": "TV",
					"reference": "Microsoft.Xbox.LiveTV_8wekyb3d8bbwe!Microsoft.Xbox.LiveTV.Application"
				},
				{
					"name": "Dashboard",
					"reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application"
				},
				{
					"name": "Plex",
					"reference": "CAF9E577.PlexforXbox_aam28m9va5cke!App"
				},
				{
					"name": "Youtube",
					"reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App"
				},
				{
					"name": "Netflix",
					"reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App"
				},
				{
					"name": "Amazon Prime",
					"reference": "AmazonVideo.AmazonVideoUK_pwbj9vvecjh7j!App"
				},
                                {
					"name": "Disney",
					"reference": "Disney.37853FC22B2CE_6rarf9sa4v8jt!App"
				},
                                {
					"name": "BBC iPlayer",
					"reference": "BBCMobileApps.BBCIPLAYER_wzgfedwv7gft2!App"
				},
				{
					"name": "BluRay",
					"reference": "Microsoft.BlurayPlayer_8wekyb3d8bbwe!Xbox.BlurayPlayer.Application"
				},
                                {
					"name": "All4",
					"reference": "CHANNELFOURTELEVISIONCOMP.All4_e1252dwpj85a4!vstest.executionengine.universal.App"
				},
                                {
					"name": "Minecraft",
					"reference": "Minecraft_zjr0dfhgjwvde!App"
				},
                                {
					"name": "COD WII",
					"reference": "shg2SubmissionENFR_ht1qfjb0gaftw!S2Boot"
				},
				{
					"name": "COD WZ",
					"reference": "iw8Submission-EN-FR_ht1qfjb0gaftw!iw8"
				},
                                {
					"name": "Fortnite",
					"reference": "Fortnite_d5xxtpggmzx6p!AppFortnite"
				},
                                {
					"name": "GTA V",
					"reference": "GTA-V_vesz1v3mcwykm!GTAV"
				}
			]
		}

**Comment by JimmyEyeball** [comment]
![IMG_0807](https://user-images.githubusercontent.com/50030249/81249241-1d17ca00-9016-11ea-9058-dcbc3e9a4180.PNG)

**Comment by grzegorz914** [comment]
You can add max. 96position in the list, I have tested this and Your config work Ok.

**Comment by grzegorz914** [comment]
I CLOSED this, because tested Your config and all working as excepted.

**Comment by JimmyEyeball** [comment]
Yes tried and tested Thank You I just had to delete then add them again for the list to update....
