### ISSUE TITLE
RESTful command

### ISSUE THREAD

**Issue by ffichman** [grzegorz914/homebridge-xbox-tv#213]
Hello i try to do a command from terminal to homebridge over RESTful to power on and off. But im receive a error.
curl -X POST http://[homebridge]:3000/Power -H "Content-Type: application/json" -d '{"Power": true}'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot POST /Power</pre>
</body>
</html>

**Comment by grzegorz914** [comment]
`curl -X POST http://[homebridge]:3000/ -H "Content-Type: application/json" -d '{"Power": true}`

**Comment by ffichman** [comment]
curl -X POST http://10.20.0.130:3000/ -H "Content-Type: application/json" -d '{"Power": true}


quote>

**Comment by grzegorz914** [comment]
The child bridge have nothing to do, it working as expected

**Comment by ffichman** [comment]
Ok. tx for helping.
