### ISSUE TITLE
How do you find Reference Values?

### ISSUE THREAD

**Issue by fh9g12** [grzegorz914/homebridge-xbox-tv#22]
How do I find the refernce values for apps I would like to open? ()                        

"name": "GTA V",
"reference": "GTA-V_vesz1v3mcwykm!GTAV" <- how do you find this?

**Comment by grzegorz914** [comment]
Open log in homebridge, open app on console and look in the log.

**Comment by fh9g12** [comment]
perfect, much easier than I was expecting! Thank you for the quick reply. Might I suggest you put something similar in the Readme.md, as this is very simple put not inherently obvisous (atleast to me)

**Comment by torandreroland** [comment]
This only works in debug log. Can you change the log level to info?
