### ISSUE TITLE
Randomises listening port

### ISSUE THREAD

**Issue by clldr** [grzegorz914/homebridge-xbox-tv#24]
This accessory adds to homebridge and is controllable through homebridge UI but does not show up in the Home App. I’ve noticed the port randomises to one that is not what homebridge is set to, what’s the fix for this?

**Comment by grzegorz914** [comment]
This is not a bug, that is all correct the port is dynamically set to every externalPlatformAccessory.

**Comment by clldr** [comment]
Thanks, but any reason why the accessory will not show up in home app? Only shows in homebridge UI, what am I missing?

**Comment by grzegorz914** [comment]
If U before add this accessory to the HomeKit then first rename it in config.json, restart homebridge and try to add it again.
