### ISSUE TITLE
No console response on start up 

### ISSUE THREAD

**Issue by b3nnyk22** [grzegorz914/homebridge-xbox-tv#32]
Hello 

I've managed to successfully install the plugin and have the console appear in my home app. If the console is already on I can successfully turn it off. If I try to turn it on again it doesn't work and the tile in the Home app says "No Response" with the exclamation mark. However looking at the Homebridge log it looks like the plugin is able to find the console in standby. "[5/17/2020, 9:21:17 PM] [XboxTv] Device: 192.168.0.14 Game console, get current Power state successful, state: STANDBY"

Any ideas?

Cheers

**Comment by grzegorz914** [comment]
Are U enabled Instant Power Mode in the console settings?

**Comment by b3nnyk22** [comment]
Yes sir.

**Comment by grzegorz914** [comment]
Are U get This after U press powerON

`Device: 192.168.1.6 Xbox One, booting..., response: { status: 'success' }`

if not check Your network, firewall and config.

**Comment by b3nnyk22** [comment]
After I power on the console manually I get the following: 

5/17/2020, 9:36:28 PM] [XboxTv] Device: 192.168.0.14 Game console, state: Online
[5/17/2020, 9:36:28 PM] [XboxTv] Device: 192.168.0.14 Game console, connected.
[5/17/2020, 9:36:28 PM] [XboxTv] Device: 192.168.0.14 Game console, get current Power state successful: ON
[5/17/2020, 9:36:28 PM] [XboxTv] Device: 192.168.0.14 Game console, get current App successful: Microsoft.Xbox.LiveTV_8wekyb3d8bbwe!Microsoft.Xbox.LiveTV.Application
[5/17/2020, 9:36:28 PM] [XboxTv] Device: 192.168.0.14 Game console, get current Mute state: ON
[5/17/2020, 9:36:28 PM] [XboxTv] Device: 192.168.0.14 Game console, get current Volume level: 0

Forgive me as I'm quite new to this, are there any other settings than a static ip I need to check? 

Cheers

**Comment by grzegorz914** [comment]
Are U write in config.json settings correct Live ID?

**Comment by b3nnyk22** [comment]
That was it! I had my xbox live ID not the console Live ID. Thank you! 

Does the console Name need to match the console or is that just what shows up in the Home App? 

 Cheers

**Comment by grzegorz914** [comment]
U can free to name Your console in config.json under "name" or use Config UI X to do this.
