### ISSUE TITLE
Volume not working 

### ISSUE THREAD

**Issue by mreassassin** [grzegorz914/homebridge-xbox-tv#39]
I have the volume slider in HomeKit but nothing changes with my volume when I adjust it. 3 Xbox’s same issue. If I use the volume control within the Microsoft Xbox app it works. 

Any ideas?

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv#info

**Comment by mreassassin** [comment]
I've read thru this a dozen times and still can't figure out exactly what I'm missing:

1. Speaker control is possible after You go to RC app on iPhone/iPad Speaker Service.  
-after I go to the RC app on my iPhone, am I supposed to see 'Speaker Service' somewhere?  I don't.

2. Legacy volume and mute control is possible throught extra lightbulb (slider) or using Siri Volume Service, in current api not working.
-does this mean I would need to tie another device to the one in this plugin and really this one is just controlling the other?

**Comment by grzegorz914** [comment]
1. No. Just use hardware volume button on iPhone/iPad to control volume.
2. In current api not working. (It’s implemented but not working right now).
