### ISSUE TITLE
(node:21580) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir

### ISSUE THREAD

**Issue by joffreyha** [grzegorz914/homebridge-xbox-tv#4]
Hi,
Upon installation and every boot of Homebridge in Docker the plugin throws following error:

(node:21580) UnhandledPromiseRejectionWarning: Error: EACCES: permission denied, mkdir
(node:21580) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:21580) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have however been able to add it successfully to the Home app. However it doesn't always properly show the state: of my Xbox.

Ps. thanks for the plugin!

**Comment by grzegorz914** [comment]
Please check latest version 0.1.5.

**Comment by joffreyha** [comment]
@grzegorz914 I can confirm it's fixed, running v0.1.9 now, issue can be closed; many thanks!
