### ISSUE TITLE
Not an issue just a question

### ISSUE THREAD

**Issue by RUGMJ7443** [grzegorz914/homebridge-xbox-tv#42]
what is the link to the app I cant find it

**Comment by grzegorz914** [comment]
Just look in the log if Switch between apps

**Comment by RUGMJ7443** [comment]
What exactly am I looking for?

**Comment by RUGMJ7443** [comment]
also where does it show the current app inside of apple home?

**Comment by grzegorz914** [comment]
Homebridge log

**Comment by RUGMJ7443** [comment]
oh... is it possible to get it to show on apple home

**Comment by grzegorz914** [comment]
No, install config-ui-x

**Comment by RUGMJ7443** [comment]
ok thanks for the work on this prodject
