### ISSUE TITLE
Device name Missing?

### ISSUE THREAD

**Issue by lukew5609** [grzegorz914/homebridge-xbox-tv#44]
Hi, I'm having some issues getting this to discover my xbox. In the error log it says "Device name missing" I have checked the name, ip address and live id and it looks ok. I am running the latest version of hoobs, could this be the issue? Please see config below

{
            "platform": "XboxTv",
            "plugin_map": {
                "plugin_name": "homebridge-xbox-tv"
            },
            "devices": [
                [
                    {
                        "name": "XboxOne",
                        "host": "192.168.0.0",
                        "xboxliveid": "FD000000000",
                        "volumeControl": true,
                        "switchInfoMenu": true,
                        "inputs": [
                            {
                                "name": "Dashboard",
                                "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                                "type": "HOME_SCREEN"
                            },
                            {
                                "name": "Settings",
                                "reference": "Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application",
                                "type": "OTHER"
                            },
                            {
                                "name": "Spotify",
                                "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App",
                                "type": "APPLICATION"
                            },
                            {
                                "name": "YouTube",
                                "reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App",
                                "type": "APPLICATION"
                            },
                            {
                                "name": "Netflix",
                                "reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App",
                                "type": "APPLICATION"
                            },
                            {
                                "name": "GTA V",
                                "reference": "GTA-V_vesz1v3mcwykm!GTAV",
                                "type": "APPLICATION"
                            },
                            {
                                "name": "All4",
                                "reference": "CHANNELFOURTELEVISIONCOMP.All4_e1252dwpj85a4!vstest.executionengine.universal.App",
                                "type": "APPLICATION"
                            },
                            {
                                "name": "Amazon Prime",
                                "reference": "AmazonVideo.AmazonVideoUK_pwbj9vvecjh7j!App",
                                "type": "APPLICATION"
                            },
                            {
                                "name": "BBC iPlayer",
                                "reference": "BBCMobileApps.BBCIPLAYER_wzgfedwv7gft2!App",
                                "type": "APPLICATION"
                            }
                        ]
                    }
                ]
            ]
        }
    ]
}

**Comment by grzegorz914** [comment]
Try this one:

```
{
"platform": "XboxTv",
"plugin_map": {
"plugin_name": "homebridge-xbox-tv"
},
"devices": [
{
"name": "XboxOne",
"host": "192.168.0.0",
"xboxliveid": "FD000000000",
"volumeControl": true,
"switchInfoMenu": true,
"inputs": [
{
"name": "Dashboard",
"reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
"type": "HOME_SCREEN"
},
{
"name": "Settings",
"reference": "Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application",
"type": "OTHER"
},
{
"name": "Spotify",
"reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App",
"type": "APPLICATION"
},
{
"name": "YouTube",
"reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App",
"type": "APPLICATION"
},
{
"name": "Netflix",
"reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App",
"type": "APPLICATION"
},
{
"name": "GTA V",
"reference": "GTA-V_vesz1v3mcwykm!GTAV",
"type": "APPLICATION"
},
{
"name": "All4",
"reference": "CHANNELFOURTELEVISIONCOMP.All4_e1252dwpj85a4!vstest.executionengine.universal.App",
"type": "APPLICATION"
},
{
"name": "Amazon Prime",
"reference": "AmazonVideo.AmazonVideoUK_pwbj9vvecjh7j!App",
"type": "APPLICATION"
},
{
"name": "BBC iPlayer",
"reference": "BBCMobileApps.BBCIPLAYER_wzgfedwv7gft2!App",
"type": "APPLICATION"
}
]
}
]
}
]
}
```

**Comment by micbou80** [comment]
@grzegorz914 that didnt solve it for me

**Comment by grzegorz914** [comment]
As i see You use Hoobs, With Homebridge and config-ui-x all working OK.
