### ISSUE TITLE
Remote Control via Home App?

### ISSUE THREAD

**Issue by Clickbaitcake** [grzegorz914/homebridge-xbox-tv#45]
Hello,

In the ReadMe for this plugin there is what looks like a remote control which can control the xbox, I do not see this in my Home app. Is there a configuration required or am I missing it in the GUI?![image](https://user-images.githubusercontent.com/39263203/92175603-cd66d500-ee34-11ea-8294-6912bde8d7d3.png)

**Comment by grzegorz914** [comment]
Look here:

![Uploading 07868EAE-F593-4968-8A87-6DBEC4248183.jpeg…]()

**Comment by Clickbaitcake** [comment]
Thank you. Could this be explained in the ReadMe?
