### ISSUE TITLE
'Console was not found on network. Probably failed' error

### ISSUE THREAD

**Issue by Jpr1986** [grzegorz914/homebridge-xbox-tv#48]
Hi,

I've followed the setup instructions as detailed, but get the below error message when trying to turn the xbox on.

'Console was not found on network. Probably failed'

If I manually turn the console on, I can turn it off using HomeKit, but not turn it on.

Any help would be appreciated

Thanks

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv#configuration-console

**Comment by Jpr1986** [comment]
Thanks for getting back to me. I worked out that the issue was I hadn't entered the Live ID correctly. All working now.

Thanks,

Again

**Comment by Jpr1986** [comment]
Thanks for the resolution
