### ISSUE TITLE
Request: specify static port in config for listener

### ISSUE THREAD

**Issue by CyberSnek** [grzegorz914/homebridge-xbox-tv#49]
I attempt to run my homebridge behind UFW Firewall. I noticed that this app launches the listener on a new port every time Homebridge restarts.

Is it possible to specify a static port in the homebridge config for this plugin to use the same port after each homebridge restart? This will allow HomeKit to continue communication with the xbox behind a UFW Firewall.

**Comment by grzegorz914** [comment]
U can use  only range  of ports to used by Homebridge plugins: 
https://github.com/grzegorz914/homebridge-xbox-tv/blob/master/sample-config.json

Set specific port for desired plugin is not possible on plugin site, this is implemented in homebridge itself.

**Comment by CyberSnek** [comment]
Thank you so much for the fast reply. This should resolve my issue.
