### ISSUE TITLE
Xbox not picked up in Home app, but shows up fine in Config-UI_X

### ISSUE THREAD

**Issue by dossiedockett** [grzegorz914/homebridge-xbox-tv#5]

**Comment by grzegorz914** [comment]
Go to HomeKit app and add it using + symbol on home screen.
In other case change the console name in config.json and restart homebridge.

**Comment by MrDarkSkil** [comment]
I've the same issue :/ @dossiedockett have you found a solution ?

**Comment by grzegorz914** [comment]
Change the name of the device, restart homebridge and try add again.

**Comment by MrDarkSkil** [comment]
I've already tried that :) 
When I want to add my Xbox manually, it asks me for the HomeKit configuration code

**Comment by grzegorz914** [comment]
The code is the same as U set in Homebridge config.

**Comment by MrDarkSkil** [comment]
OK found.
Juste re-enter homebridge homekit code

**Comment by MrDarkSkil** [comment]
It would be nice to mention this step in the readme ? 
In any case a big thank you to you ! 
Great job and great reaction time 😄
