### ISSUE TITLE
No App Reference Logs After Update

### ISSUE THREAD

**Issue by typkrft** [grzegorz914/homebridge-xbox-tv#54]
After the latest update I seem to no longer be getting the App Reference IDs reported to the Logs after I open a program. Any help would be appreciated. Thanks.

**Comment by grzegorz914** [comment]
May be just restart HB, please post Your log in debug mode.

**Comment by typkrft** [comment]
I will upload my logs tomorrow. I do see the app in Debug mode, but not when it's turned off. 
I am see this message, but not sure if it's related. 
```(node:356) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit```

**Comment by typkrft** [comment]
Here are my Debug Logs and My config.json. It's not a huge deal as I do see them when in Debug mode, but it would be nice to turn it off. Thanks. 

Homebridge 1.2.3
Node 12.19.0 also tried with 12.18.x
npm 6.14.8
Running on Docker

[Homebridge3.zip](https://github.com/grzegorz914/homebridge-xbox-tv/files/5442985/Homebridge3.zip)

**Comment by grzegorz914** [comment]
Its show correct:

`[90m}[39m
[37m[10/27/2020, 12:38:37 AM] [39m[36m[XboxTv] [39m[90mDevice: 192.168.1.159 Downstairs Master Xbox, get current App successful: Plex Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application`

**Comment by typkrft** [comment]
Yes I see it in Debug Mode, but when its not in Debug mode I do not. I get ```(node:356) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit```.

**Comment by grzegorz914** [comment]
That hat nothing to do, this is bug in Xbox api. I will check why don’t show the app iD in log.

**Comment by grzegorz914** [comment]
Please look in the log during switch the app

**Comment by typkrft** [comment]
It seems to be working now. I think the problem was at times, it wouldn't list a reference ID, but I think maybe some apps don't display them. It seems that I am unable to launch apps though. 

I have tried adding Plex and the Dashboard, it says that it has been successfully set, but does the app does not change.

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv#info

point 5

**Comment by typkrft** [comment]
Thanks!
