### ISSUE TITLE
Packet Format Not Found error - Crashes Homebridge

### ISSUE THREAD

**Issue by mariusstrom** [grzegorz914/homebridge-xbox-tv#55]
Noticed this morning that none of my HOOBS-related items were working and the log shows an unknown packet format error.

```log
11/8/2020, 7:09:07 PM Error: [packet/packer.js] Packet format not found: 7b226d6163223a2234433a35353a43433a31393a42383a4546222c226273736964223a2237343a41433a42393a34373a32353a4446222c226368616e6e656c223a312c226970223a223139322e3136382e3135372e313634222c2273736964223a227468657374726f6d732e6f7267222c2272737369223a2d34312c2272656d6f74655f7465726d696e616c5f706f7274223a323030302c2274696d65223a313630343839313334373031312c2276657273696f6e223a22454d5745524b2d4a425f315f312d312e342e302e32372c20323032302d30352d32395432333a30363a32385a2c205a656e7472694f532d575a2d332e362e342e30222c2275756964223a2230363431333034313030303030303030343930303232303030463531333733313334333433323333227d
    at loadPacketStructure (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/packet/packer.js:22:19)
    at module.exports (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/packet/packer.js:35:21)
    at EventEmitter.<anonymous> (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/events.js:15:19)
    at EventEmitter.emit (events.js:310:20)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/xbox-smartglass-core-node/src/smartglass.js:324:30)
    at Socket.emit (events.js:310:20)
    at UDP.onMessage [as onmessage] (dgram.js:924:8)
11/8/2020, 7:09:07 PM Got SIGTERM, shutting down Bridge...
```

This is Xbox Tv plugin 1.2.39, HOOBS 3.2.9, Node 12.16.3.

**Comment by grzegorz914** [comment]
Its hoobs related problem.

**Comment by mariusstrom** [comment]
@grzegorz914 looks like it actually may be an issue with the OpenXbox/xbox-smartglass-core-node repo. I've logged an issue there: https://github.com/OpenXbox/xbox-smartglass-core-node/issues/34

**Comment by mariusstrom** [comment]
@grzegorz914 FYI this is not a HOOBS issue, looks like it was an issue with xbox-smartglass-core-node. The fix will be in release 0.6.7 (not yet released) but it's available in this commit: https://github.com/OpenXbox/xbox-smartglass-core-node/commit/f88751d7412c38d4eecbe27ca8ff47764752cddc

**Comment by grzegorz914** [comment]
OK, 

I have not observed this error on my site, I will update the core api as soon as will be released.

**Comment by unknownskl** [comment]
Just wanted to let you know that xbox-smartglass-core-node is updated to 0.6.7 that should fix this problem.

**Comment by grzegorz914** [comment]
OK, thanks
