### ISSUE TITLE
Input Settings missing

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-xbox-tv#58]
Hello,

I installed your plugin in Hoobs, and everything is working great, except for my Inputs.

I setup the Dashboard and Settings for INPUT, but the Settings as a separate accessory. The dashboard is present as an input. 

My configuration : 

[
    {
        "name": "Xbox Series X",
        "host": "192.168.1.2",
        "xboxliveid": "FXXXXXXXXXXX",
        "refreshInterval": 5,
        "volumeControl": 0,
        "switchInfoMenu": false,
        "inputs": [
            {
                "name": "Dashboard",
                "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                "type": "HOME_SCREEN"
            },
            {
                "name": "Settings",
                "reference": "Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application",
                "type": "OTHER"
            }
        ],
        "manufacturer": "Microsoft",
        "modelName": "Series X",
        "serialNumber": "1",
        "firmwareRevision": "10.0"
    }
]

Thanks a lot,

**Comment by grzegorz914** [comment]
What is The question?

**Comment by Seexelas** [comment]
Yes thanks you that was the missing settings, thanks a lot ;)
