### ISSUE TITLE
Can't add Xbox accessory to Home app

### ISSUE THREAD

**Issue by rbpltr** [grzegorz914/homebridge-xbox-tv#59]
I have configured Homebridge and can see and control the Xbox in the Accessories tab of Config UI X. However, I cannot add it to the Home app in iOS. When I try to, I just get the spinning wheel and I see this error in the Homebridge log:

```
(node:1451) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 _on_console_status listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

I have tried completely resetting and reconfiguring my Homebridge including using your `sample-config.json` with no luck.

I am using version 1.3.0 from NPM.

**Comment by grzegorz914** [comment]
The error have nothing to do with Your problem, check Your network, firewall, blocked port etc.

**Comment by rbpltr** [comment]
Xbox is running on port 29101:

```
[11/26/2020, 14:51:46] Xbox One X 9044 is running on port 29101.
[11/26/2020, 14:51:46] Please add [Xbox One X 9044] manually in Home app. Setup Code: XXX-XX-XXX
```

Which I can reach from my iPhone:

```
Robs-iPhone-11-Pro-Max:~# curl http://192.168.1.5:29101 -v
*   Trying 192.168.1.5:29101...
* Failed to set TCP_KEEPIDLE on fd 5
* Failed to set TCP_KEEPINTVL on fd 5
* Connected to 192.168.1.5 (192.168.1.5) port 29101 (#0)
> GET / HTTP/1.1
> Host: 192.168.1.5:29101
> User-Agent: curl/7.69.1
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not found
< Content-Type: text/html
< Date: Thu, 26 Nov 2020 15:05:36 GMT
< Connection: keep-alive
< Transfer-Encoding: chunked
< 
* Connection #0 to host 192.168.1.5 left intact
```

**Comment by grzegorz914** [comment]
I close this because this is not the plugin problem, check Your local network and installation.
