### ISSUE TITLE
Inputs problem

### ISSUE THREAD

**Issue by DavidMaarek** [grzegorz914/homebridge-xbox-tv#62]
Hello, first of all thank you very much for this pluggin.

I have a little problem with the inputs, I can add some, I see them on my iphone, but when I use them nothing happens on the xbox.

I specify that the on / off works correctly.

Here are some screenshots of my conf and homebridge logs when trying to use inputs.

![image](https://user-images.githubusercontent.com/17063563/103162111-18de2e00-47ec-11eb-8494-9202c05b1f96.jpeg)

![image](https://user-images.githubusercontent.com/17063563/103162115-1da2e200-47ec-11eb-9399-1c24678acfb2.jpeg)

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv#info
