### ISSUE TITLE
Where can I find the Reference codes for the Games?

### ISSUE THREAD

**Issue by Denss02** [grzegorz914/homebridge-xbox-tv#63]
Hello,

I don't know why but I do not find any of the codes. 
Also they won't show up in the Homebridge Log.
What can I do?

Denis

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv#configuration-plugin

**Comment by Denss02** [comment]
That doesn't work for me.

**Comment by Magnielcz** [comment]
I can confirm that nothing appears in the log after opening the game or app.

**Comment by Magnielcz** [comment]
> That doesn't work for me.

Homebridge has to be launched in Debug mode. Then you can see appId for new inputs.

@grzegorz914 What about adding a little note about it into step 6 in readme? 

I will inspect further why is not working launching apps for me.

**Comment by grzegorz914** [comment]
OK, 

i will fixed this in next release.
