### ISSUE TITLE
No configuration found

### ISSUE THREAD

**Issue by Tontonpat** [grzegorz914/homebridge-xbox-tv#7]
Hello,
I install this plugin and i can't see any accessories in home.
It say that i have to had it in the app of the manufacturer?? 
In the log:
[homebridge-xbox-tv.XboxTv] No configuration found for homebridge
But:
![Capture d’écran 2020-04-03 à 10 55 48](https://user-images.githubusercontent.com/49283285/78342516-b5470d00-7599-11ea-9589-a038f2090fd0.png)

Thank you, and sorry for my english

**Comment by grzegorz914** [comment]
Your configuration is wrong, please use configuration editor from plugin

**Comment by Tontonpat** [comment]
Thank you, but where is the configuration editor ?

**Comment by grzegorz914** [comment]
If U use Himebridge-Config-UI-X the under Plugins menu, if not create correct config,

`”platforms”: [
{
    „platform”: „XboxTv”,
    „devices”: [
        {
            „name”: „Xbox One”,
            „host”: „192.168.1.6”,
            „xboxliveid”: „FD0000000000”,
            „switchInfoMenu”: true,
            „apps”: [
                {
                    „name”: „Game”,
                    „reference”: „”
                },
                {
                    „name”: „TV”,
                    „reference”: „Microsoft.Xbox.LiveTV_8wekyb3d8bbwe!Microsoft.Xbox.LiveTV.Application”
                },
                {
                    „name”: „Dashboard”,
                    „reference”: „Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application”
                },
                {
                    „name”: „App”,
                    „reference”: „”
                },
                {
                    „name”: „Spotify”,
                    „reference”: „SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App”
                },
                {
                    „name”: „Youtube”,
                    „reference”: „GoogleInc.YouTube_yfg5n0ztvskxp!App”
                },
                {
                    „name”: „Netflix”,
                    „reference”: „4DF9E0F8.Netflix_mcm4njqhnhss8!App”
                },
                {
                    „name”: „Airserver”,
                    „reference”: „F3F176BD.53203526D8F6C_p8qzvses5c8me!AirServer”
                }
            ]
        }
    ]
}

]`

**Comment by Tontonpat** [comment]
Ok, but i am on docker on Synology.
How can i make an good config?
All i want is to turn on/off the XBOX as a TV.

**Comment by grzegorz914** [comment]
The Example U have in my previous post.

**Comment by Tontonpat** [comment]
Thank you very much, it's ok now.
Do you think i can install it on a Synology?

**Comment by grzegorz914** [comment]
Why not? Read wiki please

**Comment by Tontonpat** [comment]
Sorry, but the Xbox is always in « no responding » in home. I can’t turn on.
There is nothing in log

**Comment by Tontonpat** [comment]
In fact, i can turn on, but can’t turn off. And when it’s on, home say it’s off or not responding. And i can’t change input
