### ISSUE TITLE
Cannot get xbox to appear in the home app. 

### ISSUE THREAD

**Issue by jricey** [grzegorz914/homebridge-xbox-tv#71]
![EE09A2D4-9C0B-4912-98C7-5879F717FBB5](https://user-images.githubusercontent.com/10951936/109740999-58782a80-7c20-11eb-9c44-9d46d31dae09.png)
Everything is configured as it should be. 

The xbox doesn’t appear in the app home after tapping “I don’t have a code and cannot scan” 

Do you have a work around or suggestion for this?

Here a link to my logs in HOOBS [https://imgur.com/pgW5c2b](url)

**Comment by grzegorz914** [comment]
Clear cashe, change name, restart homebridge and try again.

**Comment by jricey** [comment]
Winner winner!

thanks for your help!
