### ISSUE TITLE
Error: send EHOSTUNREACH 

### ISSUE THREAD

**Issue by ixy055** [grzegorz914/homebridge-xbox-tv#75]
Hey!

I love your work on this amazing plugin, but I am running into an issue where homebridge is restarted due to the xbox plugin. I have disabled the plugin and confirmed that it is the xbox plugin that is causing this. I have put logs below. 

Platform: Windows
HB: 1.3.4
UI: 4.41.0
Xbox Plugin: 1.4.31

`[03/04/2021, 5:04:29 pm] Error: send EHOSTUNREACH 224.0.0.251:5353`
`    at doSend (dgram.js:692:16)`
`    at defaultTriggerAsyncIdScope (internal/async_hooks.js:430:12)`
`    at afterDns (dgram.js:638:5)`
`    at processTicksAndRejections (internal/process/task_queues.js:81:21)`
`[03/04/2021, 5:04:29 pm] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null`
`[03/04/2021, 5:04:34 pm] [HB Supervisor] Restarting Homebridge...`
`[03/04/2021, 5:04:34 pm] [HB Supervisor] Starting Homebridge with extra flags: -I`
`[03/04/2021, 5:04:34 pm] [HB Supervisor] Started Homebridge v1.3.4 with PID: 9556`
`Initializing HAP-NodeJS v0.9.4...`

**Comment by grzegorz914** [comment]
Please enable Debug Mode and restart The Homebridge again, because this log have nothing regarding the plugin.

**Comment by ixy055** [comment]
I didnt seen to run the logs for long enough, so, after watching the logs for about an hour, I have concluded it was an mDNS issue. I fixed this by changing the mDNS advertiser to Ciao. Sorry for the stuff around. Great work with the plugin!
