### ISSUE TITLE
We’re unable to complete your request error when trying to set up webapi

### ISSUE THREAD

**Issue by notorioustubze** [grzegorz914/homebridge-xbox-tv#76]
![66D427DB-49FA-44A0-A968-7517F868A80C](https://user-images.githubusercontent.com/53260708/114318057-11286800-9b03-11eb-9b7c-5b208b6c6e4a.png)

**Comment by grzegorz914** [comment]
Please post Your config, and steps to reproduce this.

**Comment by notorioustubze** [comment]
Apologies, 

config is below to recreate - I enabled web api, reset homebridge and clicked the link that appeared in the log after the restart it then take me to the page previously posted.

 "devices": [
                {
                    "name": "XboxOne",
                    "host": "192.168.20.129",
                    "xboxliveid": "*********",
                    "refreshInterval": 5,
                    "disableLogInfo": true,
                    "xboxWebApiEnabled": true,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Dashboard",
                            "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                            "type": "HOME_SCREEN"
                        },
                        {
                            "name": "Settings",
                            "reference": "Microsoft.Xbox.Settings_8wekyb3d8bbwe!Xbox.Settings.Application",
                            "type": "OTHER"
                        },
                        {
                            "name": "YouTube",
                            "reference": "GoogleInc.YouTube_yfg5n0ztvskxp!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Netflix",
                            "reference": "4DF9E0F8.Netflix_mcm4njqhnhss8!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Plex",
                            "reference": "CAF9E577.PlexforXbox_aam28m9va5cke!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Bluray",
                            "reference": "Microsoft.BlurayPlayer_8wekyb3d8bbwe!Xbox.BlurayPlayer.Application",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "All4",
                            "reference": "CHANNELFOURTELEVISIONCOMP.All4_e1252dwpj85a4!vstest.executionengine.universal.App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Amazon Prime",
                            "reference": "AmazonVideo.AmazonVideoUK_pwbj9vvecjh7j!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Disney",
                            "reference": "Disney.37853FC22B2CE_6rarf9sa4v8jt!App",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "BBC iPlayer",
                            "reference": "BBCMobileApps.BBCIPLAYER_wzgfedwv7gft2!App",
                            "type": "APPLICATION"
                        }
                    ],
                    "manufacturer": "Microsoft",
                    "modelName": "Xbox One"
                }
            ],
            "platform": "XboxTv"
        },
        {

**Comment by grzegorz914** [comment]
Copy the part after ?code= from the response URL and paste it in to the xboxWebApiToken in plugin config, save and restart Homebridge and try open the URL again.

**Comment by jp-studios** [comment]
There is no ?code= anywhere to be found in the url. I'm encountering the same issue.

**Comment by grzegorz914** [comment]
Please post the url from Your web browser after U open the link from homebridge console.

**Comment by smtony** [comment]
Figured it out -- easy fix. 

The link displayed in your logs shows as: https://login.live.com/oauth20_authorize.srf?client_id=5e5ead27-ed60-482d-b3fc-702b28a97404&response_type=code&approval_prompt=auto&scope=XboxLive.signin%20XboxLive.offline_access&redirect_**uri**=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fcallback:

There seems to be a typo, as the error on the microsoft page shows. The typo is in "redirect_IRI" URL is spelled with an i instead of an l. simply change the i to an "l" in the browser and it'll let you log in and grab the code.

**Comment by smtony** [comment]
> 
> 
> Please post the url from Your web browser after U open the link from homebridge console.

https://login.live.com/oauth20_authorize.srf?client_id=5e5ead27-ed60-482d-b3fc-702b28a97404&response_type=code&approval_prompt=auto&scope=XboxLive.signin%20XboxLive.offline_access&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Fauth%2Fcallback:
