### ISSUE TITLE
Inputs/Sources do not work

### ISSUE THREAD

**Issue by chinedu40** [grzegorz914/homebridge-xbox-tv#79]
I have enable xboxWebApiEnabled and authenticated. 

When trying to change sources via mobile phone to an application or game, a blank microsoft store app is launch instead. 

Please advise.

**Comment by grzegorz914** [comment]
Your config?

**Comment by chinedu40** [comment]
{
            "devices": [
                {
                    "name": "Xbox One X",
                    "host": "XXXXXXXX",
                    "xboxliveid": "XXXXXXXXX",
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "xboxWebApiEnabled": false,
                    "volumeControl": 1,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Spotify",
                            "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App",
                            "type": "APPLICATION"
                        }
                    ],
                    "manufacturer": "Microsoft Corporation"
                },
                {
                    "name": "Xbox Series X",
                    "host": "XXXXXXXXX",
                    "xboxliveid": "XXXXXXXXXXXXXX",
                    "xboxWebApiToken": "XXXXXXXXXXXXXXX",
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "xboxWebApiEnabled": true,
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Spotify",
                            "reference": "SpotifyAB.SpotifyMusic-forXbox_zpdnekdrzrea0!App",
                            "referenceId": "1693425033",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "TV From Sky",
                            "reference": "NOWTV.TVfromSky_k6nsketb5gh92!App",
                            "referenceId": "1869657338",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Dashboard",
                            "reference": "Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application",
                            "referenceId": "1693425033",
                            "type": "HOME_SCREEN"
                        },
                        {
                            "name": "Fifa 21",
                            "reference": "ElectronicArtsMobile.FIFA21Scarlett_q5ha1ztykcgvj!FIFAGame.Main",
                            "referenceId": "2137885631",
                            "type": "APPLICATION"
                        }
                    ],
                    "manufacturer": "Microsoft Corporation"
                }
            ],
            "platform": "XboxTv"
        },

**Comment by grzegorz914** [comment]
Please also post Your log during switch the input.

**Comment by chinedu40** [comment]
[4/17/2021, 9:40:41 PM] [XboxTv] Device: 192.168.86.21 Xbox Series X, set Dashboard error: { status: 401, body: '' }
[4/17/2021, 9:41:43 PM] [XboxTv] Device: 192.168.86.21 Xbox Series X, set new App error: { status: 401, body: '' }

**Comment by chinedu40** [comment]
after removing and then doing it again i get the same blank microsoft store with the following log
[4/17/2021, 9:53:07 PM] [XboxTv] Device: 192.168.86.21 Xbox Series X, set new App successful, name: TV from Sky, reference: NOWTV.TVfromSky_k6nsketb5gh92!App, referenceId: 1869657338
[4/17/2021, 9:54:52 PM] [XboxTv] Device: 192.168.86.21 Xbox Series X, set Dashboard successful, name: Dashboard, reference: Xbox.Dashboard_8wekyb3d8bbwe!Xbox.Dashboard.Application
[4/17/2021, 9:54:55 PM] [XboxTv] Device: 192.168.86.21 Xbox Series X, set new App successful, name: FIFA 21, reference: ElectronicArtsMobile.FIFA21Scarlett_q5ha1ztykcgvj!FIFAGame.Main, referenceId: 2137885631
[4/17/2021, 9:55:11 PM] [XboxTv] Device: 192.168.86.21 Xbox Series X, get current Power state successful, state: ON
[4/17/2021, 9:55:11 PM] [XboxTv] Device: 192.168.86.21 Xbox Series X, get current App successful, name: Spotify, reference: Microsoft.storify_8wekyb3d8bbwe!App, referenceId: 1693425033


Going to dashboard works, but apps eg fifa21, nowtv etc do not
