### ISSUE TITLE
No answer...

### ISSUE THREAD

**Issue by netRunner0** [grzegorz914/homebridge-xbox-tv#8]
![IMG_0578](https://user-images.githubusercontent.com/44049295/78502217-5d66fc80-7779-11ea-9979-8cb53f1a0d95.jpeg)
Thanks for working on the plugin!

It does not always turn on (there is no answer, the prefix is connected by a wire)

If you select an input (for example, dashboard), it will be like this:

**Comment by grzegorz914** [comment]
Check latest update 0.1.5

**Comment by netRunner0** [comment]
Yes, I checked on this version (it was even worse before))

**Comment by grzegorz914** [comment]
Please remove and at it again the app to the HomeKit.

**Comment by netRunner0** [comment]
Now the prefix is turned off, but it shows that it is turned on
If you turn it off - no answer

**Comment by netRunner0** [comment]
![IMG_0587](https://user-images.githubusercontent.com/44049295/78982733-2ce9de80-7b3c-11ea-9797-a9a536600834.gif)

**Comment by netRunner0** [comment]
Works good
However, after some time, the prefix goes into "deep sleep" (quick wakeup is enabled in the settings) and it becomes inactive in the homekit 🤷‍♂️
