### ISSUE TITLE
WebApiToken -> How to check if it worked

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-xbox-tv#87]
Hi,

I need a bit of help to understand if what I did for web api token setup is right. 

I setup the last version of the plugin, did the webapitoken setup, restarted the HB instance.

Here is what the log is saying :
                       
[01/06/2021, 18:52:58] [XboxTv] Device: 192.168.1.2 Galaxy-Xbox, authenticated and web api enabled.

So I think it has worked, but how do I see the benefits when this is enabled ?

Thanks a lot,

**Comment by grzegorz914** [comment]
All is described in the readme.

**Comment by grzegorz914** [comment]
If You successfully authorized, you can switch between the apps.
