### ISSUE TITLE
Question on Siri vocal commands to launch Xbox apps

### ISSUE THREAD

**Issue by jeremypoulain** [grzegorz914/homebridge-xbox-tv#88]
Hi & thanks a lot for the amazing work behind this plugin!At this stage, I've managed to configure my Xbox and add games/applications and to manually launch it from the homekit UI - but I have a question regarding Siri & vocal commands : Can we launch games & app from Siri, and if yes, which vocal command do you use? I tried several things but without any success for the moment.Thanks in advance!

**Comment by mreassassin** [comment]
I would think there's gotta be a way to do this with shortcuts.  I'm gonna look into this one too!

**Comment by grzegorz914** [comment]
Siri voice control working only if You use Legacy Volume control as Fan or Brightness.

**Comment by mreassassin** [comment]
This also works nicely if you enable buttons. Then you can even create custom scenes to say custom phrases to Siri like "play Apex in the living room" for example. 
GG!
