### ISSUE TITLE
Xbox not showing up on home app, but showing up and working on homebridge accessories.

### ISSUE THREAD

**Issue by snjyr123** [grzegorz914/homebridge-xbox-tv#89]
I enabled it and got all the settings right (I think), it works turning off and on on homebridge, but doesn't show up in the app.

**Comment by grzegorz914** [comment]
Are You add it to the HomeKit app?

**Comment by nikoxlt** [comment]
Hi there, same issue here, i see it on Homebridge, but can't reach it in Apple Home

**Comment by grzegorz914** [comment]
You need add it to the HomeKit, does not appear automatically. Please read readme.
