### ISSUE TITLE
latest update not compatible with Xbox Series X?

### ISSUE THREAD

**Issue by mreassassin** [grzegorz914/homebridge-xbox-tv#92]
after the latest update I can't add my series X.  I've tried renaming it and using default settings but it doesn't ask for authentication.  i have multiple xbox ones that i was able to add one by one. it's only the series X that now will not cooperate.  any ideas?

homebridge v. 1.3.4
xbox tv v. 1.6.1

**Comment by grzegorz914** [comment]
I have both One X and Series X and both working correct. Try remove cashe in Homebridge.

**Comment by mreassassin** [comment]
I tried that as well.  it's showing up as loading by xboxtv but that's about it.  no auth and not showing up in homekit

**Comment by mreassassin** [comment]
nevermind me... at one point i set my IP to auto and it changed...  I updated the IP and now it's fine.  sorry for the bother.  thanks for the awesome plugin.  Also I've been waiting for this update!
