### ISSUE TITLE
signing in is required to do more than turn on/off

### ISSUE THREAD

**Issue by mreassassin** [grzegorz914/homebridge-xbox-tv#93]
Is signing in required in order to use the app switching and volume functionality? 

I have a password on my main account so the first thing i see on the screen is now the password prompt.  
I do have multiple family member accounts that aren't password protected.  I'm wondering if I need to use their xbox ID to get the app to call their profile instead?  

is there a way to not call any profile and let xbox prompt if the app requires a sign in?

**Comment by grzegorz914** [comment]
Yes, the console need to be logged in to the account.

**Comment by mreassassin** [comment]
Is there any way to force it to log into a family members account? Or is the live/console ID tied to the main account holder?

**Comment by grzegorz914** [comment]
I think You can set on console itself which account will be logged automatically after power on

**Comment by mreassassin** [comment]
I've also tried that but the app seems to override it by asking for my password even tho my family member is already logged in. The app keeps asking for my password In order to work. 

I'm wondering if this is also why my Xboxes now show up as not responding unless I manually power them on? Maybe? That didn't used to happen.

**Comment by grzegorz914** [comment]
are You sure You have permit remote control on xbox settings, and instant power on

**Comment by mreassassin** [comment]
Yes I had to log into the other accounts and turn it on for each. I'll triple check but I'm pretty sure. I did notice that the console/device ID is the same for all of us. Which led me to believe the primary account bolder is probably tied to that ID. Maybe?

**Comment by mreassassin** [comment]
Ok I checked again. Remote enabled and infant on for all accounts. The Xbox will sign in whoever I set to be instantly signed in when powered on BUT the app still requires my account to be logged in. The only way I've found to make this work seamlessly is to turn off my password on my Xbox. Which I don't wanna do on each console since I have credit card info tied to it. 

Any way you can think to not force anybody to sign in? Kinda like manually turning on the Xbox.

**Comment by mreassassin** [comment]
True. It's still not ideal for my situation though. It's kinda the reason we have separate accounts. Separate permissions and friends and games etc. 

I may just need to revert back to a previous version that didn't require the sign in on my account. Switching apps on the console via HomeKit is nice but not needed if I need to compromise my account for it. Im still hopeful there's a better solution though. I'll keep an eye on this. Thanks!

**Comment by grzegorz914** [comment]
Just disable webapi in config and try again.

**Comment by mreassassin** [comment]
any recommendation on how to UN-authorize?  I've tried everything from renaming my devices to putting in a made up token to uninstalling the plugin entirely...  each time I get 'connected and authenticated'.

I'm pretty sure this will be the answer to my issue if I can just get the plugin logged out of my xbox account and to allow me to re auth with a different xbox account.

**Comment by grzegorz914** [comment]
Remove authToken file in /var/lib/Homebridge/xboxTv

**Comment by grzegorz914** [comment]
Also remove xboxWebApiToken in config.json

**Comment by mreassassin** [comment]
that was absolutely the workaround I needed!  I now have different xbox's using different family members accounts when using the HK app.  I kept one xbox using my own account and took off the password (on just that one xbox) since I'm the main one that uses that one console.  

I had to delete each authToken file.
sign into the xbox account I wanted to use on each console (one by one)
autorize each one (signing out/in after each auth)
add token and restart (per instructions)

now each xbox signs into a different xbox account that doesn't require a password!  
I also tested that this doesn't ruin anybody's game in case they were signed in and I used HK to switch the xbox app.  I'll need to be careful not to switch from one game to another though, cause that does kill the current game.  wish there was some sort of warning in case this happens accidentally...

I wish I could split the tiles (show as seperate tiles) in HK so I could use siri to launch titles directly, without having to make a 'shortcut'.  probably would work the same with alexa.  I saw somebody else's issue on that...  maybe on a future update?

thank you for all the help!

**Comment by grzegorz914** [comment]
You can set buttons as separate tile for apps/inputs.

**Comment by mreassassin** [comment]
> 
> 
> You can set buttons as separate tile for apps/inputs.

how do I find the oneStoreProductId?  
for the input list I was using 'Apex_zwks512sysnyr!r5.App' for Apex Legends. that doesn't work as a button though.

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-xbox-tv#configuration-and-enable-web-api-control
