### ISSUE TITLE
Cannot configure plugin

### ISSUE THREAD

**Issue by devonhumes** [grzegorz914/homebridge-xbox-tv#95]
I'm probably not understanding the configuration steps, but I'm trying to get started for the first time. I install the plugin and the configuration shows up, but nothing else happens. I cannot click on any of the buttons (there is a JavaScript error in the console) and there are no HomeBridge logs for the plugin. What am I doing wrong?

![image](https://user-images.githubusercontent.com/693754/128800045-89093061-4fc5-4cfa-9e56-75eedcdc38e3.png)

![image](https://user-images.githubusercontent.com/693754/128800049-eeb68162-a38d-480a-91aa-6b03b1890276.png)

![image](https://user-images.githubusercontent.com/693754/128800052-a5596981-57a5-446d-a101-decacb0d89a5.png)

**Comment by devonhumes** [comment]
FYI, I've attempted to reinstall several times.

**Comment by devonhumes** [comment]
I copied and pasted the sample config and something at least showed up, but the when I click Get Token I get this error message.

![image](https://user-images.githubusercontent.com/693754/128800795-5897898a-60ee-485c-abd6-a72b99fd014c.png)

**Comment by grzegorz914** [comment]
Do not write example Web api token, You. need generate your own after configure and add console to the Home.app

**Comment by devonhumes** [comment]
I realize that. I can’t get it to work and I must be missing something. See
my original post.

**Comment by grzegorz914** [comment]
What happened after press Show Config button?

**Comment by devonhumes** [comment]
Nothing happens when I click that button.

**Comment by grzegorz914** [comment]
Try update

**Comment by devonhumes** [comment]
Already tried that. I’m fully up to date.

**Comment by grzegorz914** [comment]
try again wit step by step instruction
