### ISSUE TITLE
Error in logs

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-xbox-tv#96]
Hi,

I have this error in the logs since the last update : 

" [8/10/2021, 9:21:32 AM] [XboxTv] Device: 192.168.1.2 Xbox Series X, getInstalledApps error: {
  status: 429,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "ThrottledTryAgain",\r\n' +
    '    "errorMessage": "DocumentDataAccess::GetItemAsync: The request rate is too large. Please retry after sometime."\r\n' +
    '  },\r\n' +
    '  "result": [],\r\n' +
    '  "agentUserId": null\r\n' +
    '}'
}
[8/10/2021, 9:30:07 AM] [XboxTv] Device: 192.168.1.2 Xbox Series X, getInstalledApps error: {
  status: 429,
  body: '{\r\n' +
    '  "status": {\r\n' +
    '    "errorCode": "ThrottledTryAgain",\r\n' +
    '    "errorMessage": "DocumentDataAccess::GetItemAsync: The request rate is too large. Please retry after sometime."\r\n' +
    '  },\r\n' +
    '  "result": [],\r\n' +
    '  "agentUserId": null\r\n' +
    '}'
}

Here is the config pour the plugin : 

                    "name": "Xbox Series X",
                    "host": "192.168.1.2",
                    "xboxliveid": "XXX",
                    "xboxWebApiToken": "XXX",
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "webApiControl": true,
                    "switchInfoMenu": false,
                    "getInputsFromDevice": true,
                    "rebootControl": true
               

Thanks for the help, take care !

**Comment by grzegorz914** [comment]
please reduce the refresh rate, the request limit my Microsoft is reached
