### ISSUE TITLE
Cannot configure plugin

### ISSUE THREAD

**Issue by bjoernmayer** [grzegorz914/homebridge-xbox-tv#97]
Probably related to #95, although I am not sure why this one was closed.

I am unable to add **any** configuration. The buttons in the configuration just don't do anything.

https://user-images.githubusercontent.com/20116376/129023212-6f6f73a5-df75-41ba-8e64-17ed7b299a1b.mov

**Comment by grzegorz914** [comment]
Noobs?

**Comment by grzegorz914** [comment]
try 1.8.29

**Comment by bjoernmayer** [comment]
No Hoobs.
Same result with 1.6.29

**Comment by grzegorz914** [comment]
please add the sample-config.json  manually to the config.json and try again, I don't know why but if the plugin is not configured the schema doesn't work.

**Comment by bjoernmayer** [comment]
The default config showed up. Yet, all buttons and text fields except "Show config" were not working.
I did get it working though afterall.

**Comment by grzegorz914** [comment]
Remove default Web Api token

**Comment by Hazza42** [comment]
Same issue here. There were a bunch of weirdly named input devices listed on my Xbox inside Homekit (like "Dashboard 3" and "Settings 2") so I decided to do a clean install of homebridge-xbox-tv and I'm now met with this. Tried manually restoring the config I had before but the menu stays blank and un-editable.
