### ISSUE TITLE
can't find the APi Authentication URL

### ISSUE THREAD

**Issue by eightball11854** [grzegorz914/homebridge-xbox-tv#98]
where is it supposed to be located?

Using Homebridge for MacOS

**Comment by grzegorz914** [comment]
All is in the readme described or use wizard in plugin config to authenticate console.

**Comment by jdshkolnik** [comment]
@grzegorz914 I'm following the instructions for manual authorization and hitting the same issue as the original poster; there's no authorization URI in the console log, just a bunch of errors.

**Comment by grzegorz914** [comment]
Post the log please and config

**Comment by jdshkolnik** [comment]
I found the problem. Your readme has "Required if xboxWebApiEnabled enabled." but you really mean "webApiControl"!

**Comment by grzegorz914** [comment]
Yes, was wrong description, already changed in Readme.
