### ISSUE TITLE
Please improve commit messages & change log.

### ISSUE THREAD

**Issue by dsully** [grzegorz914/homebridge-xbox-tv#99]
Hi - first of all, thanks for this plugin!

It'd be great if commit messages could be more than just "bump". It's unfortunately to very descriptive.

homebridge-config-x also grabs the changelog and tries to match it with the version that has been released. This hasn't been in sync for some time. If you're able to do that, it'd be much appreciated.

**Comment by grzegorz914** [comment]
OK.
